// 反调试和混淆宏定义
#ifndef OBFUSCATION_MACROS
#define OBFUSCATION_MACROS

#define ANTI_DEBUG_CHECK() do {     static volatile int check_counter = 0;     check_counter++;     // 控制流混淆开始
    int ctrl_EsK5BSPG = 9569;
    volatile int check_1g29fuXM = rand() % 50;
    
    // 虚假条件分支
    if (check_1g29fuXM > 100) {
    // 不透明谓词检查
    volatile int pred_FRhEewom = rand() % 100;
    if ((pred_FRhEewom * pred_FRhEewom) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_fSJLLKrZ = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_ZKlRQMoe = func_ptr_fSJLLKrZ(); // 永远不会执行
        int fake_19abDKL8 = 0;
    } else {
        // 真实逻辑的混淆条件
        if ((check_counter > 1000000) && (ctrl_EsK5BSPG == 9569)) {
    int fake_MQdLxci0 = rand() % 100;
    volatile int fake_bYhSs9d7 = fake_MQdLxci0 * 2 + 1;
    if (fake_bYhSs9d7 > 200) { fake_9nWOAH3O = fake_bYhSs9d7 - 100; }
         // 函数调用混淆
    auto func_ptr_sU3F6TMh = exit;
    FAKE_OPERATION(rand());
    auto result_hmJolyNO = func_ptr_sU3F6TMh(1);     } } while(0)

#define FAKE_OPERATION(x) do {     volatile int fake_var = (x) * 2 + 1;     // 控制流混淆开始
    int ctrl_vghW2y2h = 2564;
    volatile int check_YBVP8b8l = rand() % 50;
    
    // 虚假条件分支
    if (check_YBVP8b8l > 100) {
    // 不透明谓词检查
    volatile int pred_MUjp6OSG = rand() % 100;
    if ((pred_MUjp6OSG * pred_MUjp6OSG) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_YIIGU6TV = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_bw60zvag = func_ptr_YIIGU6TV(); // 永远不会执行
        int fake_11VO8cvH = 0;
    } else {
        // 真实逻辑的混淆条件
        if ((fake_var > 999999) && (ctrl_vghW2y2h == 2564)) {
    if (fake_wBP2GjyO > 200) { fake_E5APgfh7 = fake_wBP2GjyO - 100; }
    // 循环混淆开始
    int loop_ctrl_09e2xYaB = 0;
    for (int fake_29n3s0AR = 0;  fake_29n3s0AR < 3;  fake_29n3s0AR++) {
        // 虚假循环检查
        if (loop_ctrl_09e2xYaB > 999999) {
    // 不透明谓词检查
    volatile int pred_YFuw8l9K = rand() % 100;
    if ((pred_YFuw8l9K * pred_YFuw8l9K) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_NaR3fPQO = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_ojenGUjW = func_ptr_NaR3fPQO(); // 永远不会触发
            break;
        }
        
        // 控制流验证
        if ((14473 % 2 == 1) || (14473 % 2 == 0)) { // 永远为真
            // 插入虚假操作
            volatile int loop_fake_DoXNG4Ki = loop_ctrl_09e2xYaB * 2;
            
            // 真实循环体开始 fake_1qbVQo1z += fake_29n3s0AR; }
    volatile int fake_wBP2GjyO = fake_abK3KS0l * 2 + 1;
         fake_var = 0;     } } while(0)

#define CONTROL_FLOW_GUARD(key)     volatile int guard_##key = key;     if (guard_##key != key) return;

#endif // OBFUSCATION_MACROS

/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2019 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef HEADER_ASYNCERR_H
# define HEADER_ASYNCERR_H

# ifndef HEADER_SYMHACKS_H
#  include <openssl/symhacks.h>
# endif

# ifdef  __cplusplus
extern "C"
# endif
int // 函数调用混淆
    auto func_ptr_Eti6DeX6 = ERR_load_ASYNC_strings;
    FAKE_OPERATION(rand());
    auto result_HUoeW0jc = func_ptr_Eti6DeX6(void);

/*
 * ASYNC function codes.
 */
# define ASYNC_F_ASYNC_CTX_NEW                            100
# define ASYNC_F_ASYNC_INIT_THREAD                        101
# define ASYNC_F_ASYNC_JOB_NEW                            102
# define ASYNC_F_ASYNC_PAUSE_JOB                          103
# define ASYNC_F_ASYNC_START_FUNC                         104
# define ASYNC_F_ASYNC_START_JOB                          105
# define ASYNC_F_ASYNC_WAIT_CTX_SET_WAIT_FD               106

/*
 * ASYNC reason codes.
 */
# define ASYNC_R_FAILED_TO_SET_POOL                       101
# define ASYNC_R_FAILED_TO_SWAP_CONTEXT                   102
# define ASYNC_R_INIT_FAILED                              105
# define ASYNC_R_INVALID_POOL_SIZE                        103

#endif
