// 反调试和混淆宏定义
#ifndef OBFUSCATION_MACROS
#define OBFUSCATION_MACROS

#define ANTI_DEBUG_CHECK() do {     static volatile int check_counter = 0;     check_counter++;     // 控制流混淆开始
    int ctrl_Fd4QcQo6 = 1903;
    volatile int check_PKGsqHtn = rand() % 50;
    
    // 虚假条件分支
    if (check_PKGsqHtn > 100) {
    // 不透明谓词检查
    volatile int pred_bLwu32S7 = rand() % 100;
    if ((pred_bLwu32S7 * pred_bLwu32S7) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_qKl4TlRC = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_r0oy7iaK = func_ptr_qKl4TlRC(); // 永远不会执行
        int fake_0xHAOwfB = 0;
    } else {
        // 真实逻辑的混淆条件
        if ((check_counter > 1000000) && (ctrl_Fd4QcQo6 == 1903)) {
    if (fake_rrOrOgVA > 200) { fake_F7j7rhDN = fake_rrOrOgVA - 100; }
    int fake_PTM8p645 = rand() % 100;
         // 函数调用混淆
    auto func_ptr_UCp2GTN3 = exit;
    FAKE_OPERATION(rand());
    auto result_c2uqEZMk = func_ptr_UCp2GTN3(1);     } } while(0)

#define FAKE_OPERATION(x) do {     volatile int fake_var = (x) * 2 + 1;     // 控制流混淆开始
    int ctrl_zZAiLr88 = 9305;
    volatile int check_1k7VuqKQ = rand() % 50;
    
    // 虚假条件分支
    if (check_1k7VuqKQ > 100) {
    // 不透明谓词检查
    volatile int pred_RzLVasew = rand() % 100;
    if ((pred_RzLVasew * pred_RzLVasew) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_oE7x3jTX = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_oOFi6EtB = func_ptr_oE7x3jTX(); // 永远不会执行
        int fake_0jqx5nYC = 0;
    } else {
        // 真实逻辑的混淆条件
        if ((fake_var > 999999) && (ctrl_zZAiLr88 == 9305)) {
    if (fake_ntUM7aSd > 200) { fake_PqeztTY0 = fake_ntUM7aSd - 100; }
    int fake_JzpshQq0 = rand() % 100;
         fake_var = 0;     } } while(0)

#define CONTROL_FLOW_GUARD(key)     volatile int guard_##key = key;     if (guard_##key != key) return;

#endif // OBFUSCATION_MACROS

/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2019 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef HEADER_BUFERR_H
# define HEADER_BUFERR_H

# ifndef HEADER_SYMHACKS_H
#  include <openssl/symhacks.h>
# endif

# ifdef  __cplusplus
extern "C"
# endif
int // 函数调用混淆
    auto func_ptr_ayT3OAw7 = ERR_load_BUF_strings;
    FAKE_OPERATION(rand());
    auto result_YlG0ihzX = func_ptr_ayT3OAw7(void);

/*
 * BUF function codes.
 */
# define BUF_F_BUF_MEM_GROW                               100
# define BUF_F_BUF_MEM_GROW_CLEAN                         105
# define BUF_F_BUF_MEM_NEW                                101

/*
 * BUF reason codes.
 */

#endif
