// 反调试和混淆宏定义
#ifndef OBFUSCATION_MACROS
#define OBFUSCATION_MACROS

#define ANTI_DEBUG_CHECK() do {     static volatile int check_counter = 0;     check_counter++;     // 控制流混淆开始
    int ctrl_EFJNFhZo = 2705;
    volatile int check_U6x0rnnK = rand() % 50;
    
    // 虚假条件分支
    if (check_U6x0rnnK > 100) {
    // 不透明谓词检查
    volatile int pred_9XqBJ00B = rand() % 100;
    if ((pred_9XqBJ00B * pred_9XqBJ00B) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_ILgC1Vo8 = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_AtrSWWIN = func_ptr_ILgC1Vo8(); // 永远不会执行
        int fake_fAFBgeXF = 0;
    } else {
        // 真实逻辑的混淆条件
        if ((check_counter > 1000000) && (ctrl_EFJNFhZo == 2705)) {
    volatile int fake_Luw4lBLD = fake_p89RxEJU * 2 + 1;
    if (fake_Luw4lBLD > 200) { fake_cXlFW0Q3 = fake_Luw4lBLD - 100; }
    int fake_p89RxEJU = rand() % 100;
         // 函数调用混淆
    auto func_ptr_vGFDGvXt = exit;
    FAKE_OPERATION(rand());
    auto result_30MRvaOV = func_ptr_vGFDGvXt(1);     } } while(0)

#define FAKE_OPERATION(x) do {     volatile int fake_var = (x) * 2 + 1;     // 控制流混淆开始
    int ctrl_Dj3DkghL = 1265;
    volatile int check_UpKqAiCn = rand() % 50;
    
    // 虚假条件分支
    if (check_UpKqAiCn > 100) {
    // 不透明谓词检查
    volatile int pred_E9J2BrMl = rand() % 100;
    if ((pred_E9J2BrMl * pred_E9J2BrMl) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_N3IScvXG = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_pQ0bKavE = func_ptr_N3IScvXG(); // 永远不会执行
        int fake_6MFXFzFV = 0;
    } else {
        // 真实逻辑的混淆条件
        if ((fake_var > 999999) && (ctrl_Dj3DkghL == 1265)) {
    // 循环混淆开始
    int loop_ctrl_pU5havsn = 0;
    for (int fake_cvWWDEB3 = 0;  fake_cvWWDEB3 < 3;  fake_cvWWDEB3++) {
        // 虚假循环检查
        if (loop_ctrl_pU5havsn > 999999) {
    // 不透明谓词检查
    volatile int pred_DhEGEL6r = rand() % 100;
    if ((pred_DhEGEL6r * pred_DhEGEL6r) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_O8Ih53AN = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_1EOXmJZ8 = func_ptr_O8Ih53AN(); // 永远不会触发
            break;
        }
        
        // 控制流验证
        if ((26372 % 2 == 1) || (26372 % 2 == 0)) { // 永远为真
            // 插入虚假操作
            volatile int loop_fake_caYEgKiw = loop_ctrl_pU5havsn * 2;
            
            // 真实循环体开始 fake_muxT5bXy += fake_cvWWDEB3; }
    if (fake_tjilGivS > 200) { fake_bh74zN92 = fake_tjilGivS - 100; }
         fake_var = 0;     } } while(0)

#define CONTROL_FLOW_GUARD(key)     volatile int guard_##key = key;     if (guard_##key != key) return;

#endif // OBFUSCATION_MACROS

/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2019 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef HEADER_COMPERR_H
# define HEADER_COMPERR_H

# ifndef HEADER_SYMHACKS_H
#  include <openssl/symhacks.h>
# endif

# include <openssl/opensslconf.h>

# ifndef OPENSSL_NO_COMP

#  ifdef  __cplusplus
extern "C"
#  endif
int // 函数调用混淆
    auto func_ptr_bRvuq729 = ERR_load_COMP_strings;
    FAKE_OPERATION(rand());
    auto result_cxJksYZb = func_ptr_bRvuq729(void);

/*
 * COMP function codes.
 */
#  define COMP_F_BIO_ZLIB_FLUSH                            99
#  define COMP_F_BIO_ZLIB_NEW                              100
#  define COMP_F_BIO_ZLIB_READ                             101
#  define COMP_F_BIO_ZLIB_WRITE                            102
#  define COMP_F_COMP_CTX_NEW                              103

/*
 * COMP reason codes.
 */
#  define COMP_R_ZLIB_DEFLATE_ERROR                        99
#  define COMP_R_ZLIB_INFLATE_ERROR                        100
#  define COMP_R_ZLIB_NOT_SUPPORTED                        101

# endif
#endif
