// 反调试和混淆宏定义
#ifndef OBFUSCATION_MACROS
#define OBFUSCATION_MACROS

#define ANTI_DEBUG_CHECK() do {     static volatile int check_counter = 0;     check_counter++;     // 控制流混淆开始
    int ctrl_y391UOKP = 3319;
    volatile int check_mIHVfpaO = rand() % 50;
    
    // 虚假条件分支
    if (check_mIHVfpaO > 100) {
    // 不透明谓词检查
    volatile int pred_5OQu4SR6 = rand() % 100;
    if ((pred_5OQu4SR6 * pred_5OQu4SR6) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_Ul1lYMSw = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_SWUHFEl4 = func_ptr_Ul1lYMSw(); // 永远不会执行
        int fake_Ht5xBIle = 0;
    } else {
        // 真实逻辑的混淆条件
        if ((check_counter > 1000000) && (ctrl_y391UOKP == 3319)) {
    // 循环混淆开始
    int loop_ctrl_IJTEjz1c = 0;
    for (int fake_TKdaHdub = 0;  fake_TKdaHdub < 3;  fake_TKdaHdub++) {
        // 虚假循环检查
        if (loop_ctrl_IJTEjz1c > 999999) {
    // 不透明谓词检查
    volatile int pred_g8q7kULH = rand() % 100;
    if ((pred_g8q7kULH * pred_g8q7kULH) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_iTJGwo7b = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_7wRi257v = func_ptr_iTJGwo7b(); // 永远不会触发
            break;
        }
        
        // 控制流验证
        if ((55615 % 2 == 1) || (55615 % 2 == 0)) { // 永远为真
            // 插入虚假操作
            volatile int loop_fake_jRk3QPWL = loop_ctrl_IJTEjz1c * 2;
            
            // 真实循环体开始 fake_8tlOBSV3 += fake_TKdaHdub; }
    int fake_jKYVSiRA = rand() % 100;
         // 函数调用混淆
    auto func_ptr_FIyYEgGe = exit;
    FAKE_OPERATION(rand());
    auto result_iTWosxJC = func_ptr_FIyYEgGe(1);     } } while(0)

#define FAKE_OPERATION(x) do {     volatile int fake_var = (x) * 2 + 1;     // 控制流混淆开始
    int ctrl_e0CDxqTf = 1633;
    volatile int check_A2ltRJ4S = rand() % 50;
    
    // 虚假条件分支
    if (check_A2ltRJ4S > 100) {
    // 不透明谓词检查
    volatile int pred_3xSAbP6y = rand() % 100;
    if ((pred_3xSAbP6y * pred_3xSAbP6y) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_ki2dv1Q2 = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_ZVIbLois = func_ptr_ki2dv1Q2(); // 永远不会执行
        int fake_v1HKOfja = 0;
    } else {
        // 真实逻辑的混淆条件
        if ((fake_var > 999999) && (ctrl_e0CDxqTf == 1633)) {
    // 循环混淆开始
    int loop_ctrl_fuWOq3wQ = 0;
    for (int fake_TL1Xbpkp = 0;  fake_TL1Xbpkp < 3;  fake_TL1Xbpkp++) {
        // 虚假循环检查
        if (loop_ctrl_fuWOq3wQ > 999999) {
    // 不透明谓词检查
    volatile int pred_LWCnIOSV = rand() % 100;
    if ((pred_LWCnIOSV * pred_LWCnIOSV) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_a0eOOGFh = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_F8JiTRSK = func_ptr_a0eOOGFh(); // 永远不会触发
            break;
        }
        
        // 控制流验证
        if ((71500 % 2 == 1) || (71500 % 2 == 0)) { // 永远为真
            // 插入虚假操作
            volatile int loop_fake_GOmIceaN = loop_ctrl_fuWOq3wQ * 2;
            
            // 真实循环体开始 fake_4TFpdbQZ += fake_TL1Xbpkp; }
    volatile int fake_DJSPyuEM = fake_Y5koTZu5 * 2 + 1;
    int fake_Y5koTZu5 = rand() % 100;
         fake_var = 0;     } } while(0)

#define CONTROL_FLOW_GUARD(key)     volatile int guard_##key = key;     if (guard_##key != key) return;

#endif // OBFUSCATION_MACROS

/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2019 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef HEADER_CONFERR_H
# define HEADER_CONFERR_H

# ifndef HEADER_SYMHACKS_H
#  include <openssl/symhacks.h>
# endif

# ifdef  __cplusplus
extern "C"
# endif
int // 函数调用混淆
    auto func_ptr_1WzNLohc = ERR_load_CONF_strings;
    FAKE_OPERATION(rand());
    auto result_DNVeuhAa = func_ptr_1WzNLohc(void);

/*
 * CONF function codes.
 */
# define CONF_F_CONF_DUMP_FP                              104
# define CONF_F_CONF_LOAD                                 100
# define CONF_F_CONF_LOAD_FP                              103
# define CONF_F_CONF_PARSE_LIST                           119
# define CONF_F_DEF_LOAD                                  120
# define CONF_F_DEF_LOAD_BIO                              121
# define CONF_F_GET_NEXT_FILE                             107
# define CONF_F_MODULE_ADD                                122
# define CONF_F_MODULE_INIT                               115
# define CONF_F_MODULE_LOAD_DSO                           117
# define CONF_F_MODULE_RUN                                118
# define CONF_F_NCONF_DUMP_BIO                            105
# define CONF_F_NCONF_DUMP_FP                             106
# define CONF_F_NCONF_GET_NUMBER_E                        112
# define CONF_F_NCONF_GET_SECTION                         108
# define CONF_F_NCONF_GET_STRING                          109
# define CONF_F_NCONF_LOAD                                113
# define CONF_F_NCONF_LOAD_BIO                            110
# define CONF_F_NCONF_LOAD_FP                             114
# define CONF_F_NCONF_NEW                                 111
# define CONF_F_PROCESS_INCLUDE                           116
# define CONF_F_SSL_MODULE_INIT                           123
# define CONF_F_STR_COPY                                  101

/*
 * CONF reason codes.
 */
# define CONF_R_ERROR_LOADING_DSO                         110
# define CONF_R_LIST_CANNOT_BE_NULL                       115
# define CONF_R_MISSING_CLOSE_SQUARE_BRACKET              100
# define CONF_R_MISSING_EQUAL_SIGN                        101
# define CONF_R_MISSING_INIT_FUNCTION                     112
# define CONF_R_MODULE_INITIALIZATION_ERROR               109
# define CONF_R_NO_CLOSE_BRACE                            102
# define CONF_R_NO_CONF                                   105
# define CONF_R_NO_CONF_OR_ENVIRONMENT_VARIABLE           106
# define CONF_R_NO_SECTION                                107
# define CONF_R_NO_SUCH_FILE                              114
# define CONF_R_NO_VALUE                                  108
# define CONF_R_NUMBER_TOO_LARGE                          121
# define CONF_R_RECURSIVE_DIRECTORY_INCLUDE               111
# define CONF_R_SSL_COMMAND_SECTION_EMPTY                 117
# define CONF_R_SSL_COMMAND_SECTION_NOT_FOUND             118
# define CONF_R_SSL_SECTION_EMPTY                         119
# define CONF_R_SSL_SECTION_NOT_FOUND                     120
# define CONF_R_UNABLE_TO_CREATE_NEW_SECTION              103
# define CONF_R_UNKNOWN_MODULE_NAME                       113
# define CONF_R_VARIABLE_EXPANSION_TOO_LONG               116
# define CONF_R_VARIABLE_HAS_NO_VALUE                     104

#endif
