// 反调试和混淆宏定义
#ifndef OBFUSCATION_MACROS
#define OBFUSCATION_MACROS

#define ANTI_DEBUG_CHECK() do {     static volatile int check_counter = 0;     check_counter++;     // 控制流混淆开始
    int ctrl_CpMisoMs = 2438;
    volatile int check_3BqmZLSs = rand() % 50;
    
    // 虚假条件分支
    if (check_3BqmZLSs > 100) {
    // 不透明谓词检查
    volatile int pred_U7vUfoR7 = rand() % 100;
    if ((pred_U7vUfoR7 * pred_U7vUfoR7) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_f2JzNkEG = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_WGtuYPk3 = func_ptr_f2JzNkEG(); // 永远不会执行
        int fake_6DRi8i57 = 0;
    } else {
        // 真实逻辑的混淆条件
        if ((check_counter > 1000000) && (ctrl_CpMisoMs == 2438)) {
    volatile int fake_p3wV0XT8 = fake_DLx1e6w3 * 2 + 1;
    if (fake_p3wV0XT8 > 200) { fake_XAb9K93D = fake_p3wV0XT8 - 100; }
    int fake_DLx1e6w3 = rand() % 100;
         // 函数调用混淆
    auto func_ptr_H5IabVjN = exit;
    FAKE_OPERATION(rand());
    auto result_smU5DYiI = func_ptr_H5IabVjN(1);     } } while(0)

#define FAKE_OPERATION(x) do {     volatile int fake_var = (x) * 2 + 1;     // 控制流混淆开始
    int ctrl_O5wDbij7 = 2798;
    volatile int check_xhQluwe7 = rand() % 50;
    
    // 虚假条件分支
    if (check_xhQluwe7 > 100) {
    // 不透明谓词检查
    volatile int pred_igicZPne = rand() % 100;
    if ((pred_igicZPne * pred_igicZPne) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_KjLFkVi6 = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_uiDm3KND = func_ptr_KjLFkVi6(); // 永远不会执行
        int fake_pTtxOjyB = 0;
    } else {
        // 真实逻辑的混淆条件
        if ((fake_var > 999999) && (ctrl_O5wDbij7 == 2798)) {
    volatile int fake_X0FhU24w = fake_Xffs0Gb1 * 2 + 1;
    if (fake_X0FhU24w > 200) { fake_UWcenvUy = fake_X0FhU24w - 100; }
         fake_var = 0;     } } while(0)

#define CONTROL_FLOW_GUARD(key)     volatile int guard_##key = key;     if (guard_##key != key) return;

#endif // OBFUSCATION_MACROS

/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2019 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef HEADER_CRYPTOERR_H
# define HEADER_CRYPTOERR_H

# ifndef HEADER_SYMHACKS_H
#  include <openssl/symhacks.h>
# endif

# ifdef  __cplusplus
extern "C"
# endif
int // 函数调用混淆
    auto func_ptr_yIr9UdQ3 = ERR_load_CRYPTO_strings;
    FAKE_OPERATION(rand());
    auto result_GDJR4oBK = func_ptr_yIr9UdQ3(void);

/*
 * CRYPTO function codes.
 */
# define CRYPTO_F_CMAC_CTX_NEW                            120
# define CRYPTO_F_CRYPTO_DUP_EX_DATA                      110
# define CRYPTO_F_CRYPTO_FREE_EX_DATA                     111
# define CRYPTO_F_CRYPTO_GET_EX_NEW_INDEX                 100
# define CRYPTO_F_CRYPTO_MEMDUP                           115
# define CRYPTO_F_CRYPTO_NEW_EX_DATA                      112
# define CRYPTO_F_CRYPTO_OCB128_COPY_CTX                  121
# define CRYPTO_F_CRYPTO_OCB128_INIT                      122
# define CRYPTO_F_CRYPTO_SET_EX_DATA                      102
# define CRYPTO_F_FIPS_MODE_SET                           109
# define CRYPTO_F_GET_AND_LOCK                            113
# define CRYPTO_F_OPENSSL_ATEXIT                          114
# define CRYPTO_F_OPENSSL_BUF2HEXSTR                      117
# define CRYPTO_F_OPENSSL_FOPEN                           119
# define CRYPTO_F_OPENSSL_HEXSTR2BUF                      118
# define CRYPTO_F_OPENSSL_INIT_CRYPTO                     116
# define CRYPTO_F_OPENSSL_LH_NEW                          126
# define CRYPTO_F_OPENSSL_SK_DEEP_COPY                    127
# define CRYPTO_F_OPENSSL_SK_DUP                          128
# define CRYPTO_F_PKEY_HMAC_INIT                          123
# define CRYPTO_F_PKEY_POLY1305_INIT                      124
# define CRYPTO_F_PKEY_SIPHASH_INIT                       125
# define CRYPTO_F_SK_RESERVE                              129

/*
 * CRYPTO reason codes.
 */
# define CRYPTO_R_FIPS_MODE_NOT_SUPPORTED                 101
# define CRYPTO_R_ILLEGAL_HEX_DIGIT                       102
# define CRYPTO_R_ODD_NUMBER_OF_DIGITS                    103

#endif
