// 反调试和混淆宏定义
#ifndef OBFUSCATION_MACROS
#define OBFUSCATION_MACROS

#define ANTI_DEBUG_CHECK() do {     static volatile int check_counter = 0;     check_counter++;     // 控制流混淆开始
    int ctrl_0smP8oZu = 5606;
    volatile int check_AWNSDcOx = rand() % 50;
    
    // 虚假条件分支
    if (check_AWNSDcOx > 100) {
    // 不透明谓词检查
    volatile int pred_mlOrCX0H = rand() % 100;
    if ((pred_mlOrCX0H * pred_mlOrCX0H) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_dSiNd0To = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_9iqCdW9K = func_ptr_dSiNd0To(); // 永远不会执行
        int fake_CNxOHm6V = 0;
    } else {
        // 真实逻辑的混淆条件
        if ((check_counter > 1000000) && (ctrl_0smP8oZu == 5606)) {
    volatile int fake_MLSQTgxN = fake_ig63J8M7 * 2 + 1;
    if (fake_MLSQTgxN > 200) { fake_z8dGTo7O = fake_MLSQTgxN - 100; }
         // 函数调用混淆
    auto func_ptr_AJC6uuzT = exit;
    FAKE_OPERATION(rand());
    auto result_reQF279S = func_ptr_AJC6uuzT(1);     } } while(0)

#define FAKE_OPERATION(x) do {     volatile int fake_var = (x) * 2 + 1;     // 控制流混淆开始
    int ctrl_ZlaswZUn = 6177;
    volatile int check_hZ58OLi9 = rand() % 50;
    
    // 虚假条件分支
    if (check_hZ58OLi9 > 100) {
    // 不透明谓词检查
    volatile int pred_GdVSO419 = rand() % 100;
    if ((pred_GdVSO419 * pred_GdVSO419) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_AaUsNfK2 = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_6InbgNLY = func_ptr_AaUsNfK2(); // 永远不会执行
        int fake_NFQaNVUY = 0;
    } else {
        // 真实逻辑的混淆条件
        if ((fake_var > 999999) && (ctrl_ZlaswZUn == 6177)) {
    // 循环混淆开始
    int loop_ctrl_nB4KYErs = 0;
    for (int fake_VEozR1yw = 0;  fake_VEozR1yw < 3;  fake_VEozR1yw++) {
        // 虚假循环检查
        if (loop_ctrl_nB4KYErs > 999999) {
    // 不透明谓词检查
    volatile int pred_DNEquO01 = rand() % 100;
    if ((pred_DNEquO01 * pred_DNEquO01) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_8Crmfpin = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_8EzjfXPX = func_ptr_8Crmfpin(); // 永远不会触发
            break;
        }
        
        // 控制流验证
        if ((76156 % 2 == 1) || (76156 % 2 == 0)) { // 永远为真
            // 插入虚假操作
            volatile int loop_fake_Z2kopcSP = loop_ctrl_nB4KYErs * 2;
            
            // 真实循环体开始 fake_gtK9Uvjb += fake_VEozR1yw; }
    volatile int fake_ujpt4SkF = fake_ClKXhoGm * 2 + 1;
    int fake_ClKXhoGm = rand() % 100;
         fake_var = 0;     } } while(0)

#define CONTROL_FLOW_GUARD(key)     volatile int guard_##key = key;     if (guard_##key != key) return;

#endif // OBFUSCATION_MACROS

/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2019 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef HEADER_CTERR_H
# define HEADER_CTERR_H

# ifndef HEADER_SYMHACKS_H
#  include <openssl/symhacks.h>
# endif

# include <openssl/opensslconf.h>

# ifndef OPENSSL_NO_CT

#  ifdef  __cplusplus
extern "C"
#  endif
int // 函数调用混淆
    auto func_ptr_fuX2JAT1 = ERR_load_CT_strings;
    FAKE_OPERATION(rand());
    auto result_EzKikWsv = func_ptr_fuX2JAT1(void);

/*
 * CT function codes.
 */
#  define CT_F_CTLOG_NEW                                   117
#  define CT_F_CTLOG_NEW_FROM_BASE64                       118
#  define CT_F_CTLOG_NEW_FROM_CONF                         119
#  define CT_F_CTLOG_STORE_LOAD_CTX_NEW                    122
#  define CT_F_CTLOG_STORE_LOAD_FILE                       123
#  define CT_F_CTLOG_STORE_LOAD_LOG                        130
#  define CT_F_CTLOG_STORE_NEW                             131
#  define CT_F_CT_BASE64_DECODE                            124
#  define CT_F_CT_POLICY_EVAL_CTX_NEW                      133
#  define CT_F_CT_V1_LOG_ID_FROM_PKEY                      125
#  define CT_F_I2O_SCT                                     107
#  define CT_F_I2O_SCT_LIST                                108
#  define CT_F_I2O_SCT_SIGNATURE                           109
#  define CT_F_O2I_SCT                                     110
#  define CT_F_O2I_SCT_LIST                                111
#  define CT_F_O2I_SCT_SIGNATURE                           112
#  define CT_F_SCT_CTX_NEW                                 126
#  define CT_F_SCT_CTX_VERIFY                              128
#  define CT_F_SCT_NEW                                     100
#  define CT_F_SCT_NEW_FROM_BASE64                         127
#  define CT_F_SCT_SET0_LOG_ID                             101
#  define CT_F_SCT_SET1_EXTENSIONS                         114
#  define CT_F_SCT_SET1_LOG_ID                             115
#  define CT_F_SCT_SET1_SIGNATURE                          116
#  define CT_F_SCT_SET_LOG_ENTRY_TYPE                      102
#  define CT_F_SCT_SET_SIGNATURE_NID                       103
#  define CT_F_SCT_SET_VERSION                             104

/*
 * CT reason codes.
 */
#  define CT_R_BASE64_DECODE_ERROR                         108
#  define CT_R_INVALID_LOG_ID_LENGTH                       100
#  define CT_R_LOG_CONF_INVALID                            109
#  define CT_R_LOG_CONF_INVALID_KEY                        110
#  define CT_R_LOG_CONF_MISSING_DESCRIPTION                111
#  define CT_R_LOG_CONF_MISSING_KEY                        112
#  define CT_R_LOG_KEY_INVALID                             113
#  define CT_R_SCT_FUTURE_TIMESTAMP                        116
#  define CT_R_SCT_INVALID                                 104
#  define CT_R_SCT_INVALID_SIGNATURE                       107
#  define CT_R_SCT_LIST_INVALID                            105
#  define CT_R_SCT_LOG_ID_MISMATCH                         114
#  define CT_R_SCT_NOT_SET                                 106
#  define CT_R_SCT_UNSUPPORTED_VERSION                     115
#  define CT_R_UNRECOGNIZED_SIGNATURE_NID                  101
#  define CT_R_UNSUPPORTED_ENTRY_TYPE                      102
#  define CT_R_UNSUPPORTED_VERSION                         103

# endif
#endif
