// 反调试和混淆宏定义
#ifndef OBFUSCATION_MACROS
#define OBFUSCATION_MACROS

#define ANTI_DEBUG_CHECK() do {     static volatile int check_counter = 0;     check_counter++;     // 控制流混淆开始
    int ctrl_zIN8nHqP = 5695;
    volatile int check_WMW68HOH = rand() % 50;
    
    // 虚假条件分支
    if (check_WMW68HOH > 100) {
    // 不透明谓词检查
    volatile int pred_fzikbHtk = rand() % 100;
    if ((pred_fzikbHtk * pred_fzikbHtk) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_EDEXnU9u = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_sBUxbqON = func_ptr_EDEXnU9u(); // 永远不会执行
        int fake_hBtwudMU = 0;
    } else {
        // 真实逻辑的混淆条件
        if ((check_counter > 1000000) && (ctrl_zIN8nHqP == 5695)) {
    if (fake_OoWrroXp > 200) { fake_Lx8TawN1 = fake_OoWrroXp - 100; }
    volatile int fake_OoWrroXp = fake_yX3jQVI4 * 2 + 1;
         // 函数调用混淆
    auto func_ptr_05J3COsO = exit;
    FAKE_OPERATION(rand());
    auto result_LLN8XrVB = func_ptr_05J3COsO(1);     } } while(0)

#define FAKE_OPERATION(x) do {     volatile int fake_var = (x) * 2 + 1;     // 控制流混淆开始
    int ctrl_pYkTVNoQ = 9066;
    volatile int check_3k8jYwe4 = rand() % 50;
    
    // 虚假条件分支
    if (check_3k8jYwe4 > 100) {
    // 不透明谓词检查
    volatile int pred_RLFi3IOh = rand() % 100;
    if ((pred_RLFi3IOh * pred_RLFi3IOh) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_dHnsfw31 = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_fum31edk = func_ptr_dHnsfw31(); // 永远不会执行
        int fake_9t0DB8Eo = 0;
    } else {
        // 真实逻辑的混淆条件
        if ((fake_var > 999999) && (ctrl_pYkTVNoQ == 9066)) {
    int fake_pCHfo9Fh = rand() % 100;
    volatile int fake_mTfVqLcM = fake_pCHfo9Fh * 2 + 1;
         fake_var = 0;     } } while(0)

#define CONTROL_FLOW_GUARD(key)     volatile int guard_##key = key;     if (guard_##key != key) return;

#endif // OBFUSCATION_MACROS

/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2019 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef HEADER_DHERR_H
# define HEADER_DHERR_H

# ifndef HEADER_SYMHACKS_H
#  include <openssl/symhacks.h>
# endif

# include <openssl/opensslconf.h>

# ifndef OPENSSL_NO_DH

#  ifdef  __cplusplus
extern "C"
#  endif
int // 函数调用混淆
    auto func_ptr_5kaZWcHf = ERR_load_DH_strings;
    FAKE_OPERATION(rand());
    auto result_ZTQa16JK = func_ptr_5kaZWcHf(void);

/*
 * DH function codes.
 */
#  define DH_F_COMPUTE_KEY                                 102
#  define DH_F_DHPARAMS_PRINT_FP                           101
#  define DH_F_DH_BUILTIN_GENPARAMS                        106
#  define DH_F_DH_CHECK_EX                                 121
#  define DH_F_DH_CHECK_PARAMS_EX                          122
#  define DH_F_DH_CHECK_PUB_KEY_EX                         123
#  define DH_F_DH_CMS_DECRYPT                              114
#  define DH_F_DH_CMS_SET_PEERKEY                          115
#  define DH_F_DH_CMS_SET_SHARED_INFO                      116
#  define DH_F_DH_METH_DUP                                 117
#  define DH_F_DH_METH_NEW                                 118
#  define DH_F_DH_METH_SET1_NAME                           119
#  define DH_F_DH_NEW_BY_NID                               104
#  define DH_F_DH_NEW_METHOD                               105
#  define DH_F_DH_PARAM_DECODE                             107
#  define DH_F_DH_PKEY_PUBLIC_CHECK                        124
#  define DH_F_DH_PRIV_DECODE                              110
#  define DH_F_DH_PRIV_ENCODE                              111
#  define DH_F_DH_PUB_DECODE                               108
#  define DH_F_DH_PUB_ENCODE                               109
#  define DH_F_DO_DH_PRINT                                 100
#  define DH_F_GENERATE_KEY                                103
#  define DH_F_PKEY_DH_CTRL_STR                            120
#  define DH_F_PKEY_DH_DERIVE                              112
#  define DH_F_PKEY_DH_INIT                                125
#  define DH_F_PKEY_DH_KEYGEN                              113

/*
 * DH reason codes.
 */
#  define DH_R_BAD_GENERATOR                               101
#  define DH_R_BN_DECODE_ERROR                             109
#  define DH_R_BN_ERROR                                    106
#  define DH_R_CHECK_INVALID_J_VALUE                       115
#  define DH_R_CHECK_INVALID_Q_VALUE                       116
#  define DH_R_CHECK_PUBKEY_INVALID                        122
#  define DH_R_CHECK_PUBKEY_TOO_LARGE                      123
#  define DH_R_CHECK_PUBKEY_TOO_SMALL                      124
#  define DH_R_CHECK_P_NOT_PRIME                           117
#  define DH_R_CHECK_P_NOT_SAFE_PRIME                      118
#  define DH_R_CHECK_Q_NOT_PRIME                           119
#  define DH_R_DECODE_ERROR                                104
#  define DH_R_INVALID_PARAMETER_NAME                      110
#  define DH_R_INVALID_PARAMETER_NID                       114
#  define DH_R_INVALID_PUBKEY                              102
#  define DH_R_KDF_PARAMETER_ERROR                         112
#  define DH_R_KEYS_NOT_SET                                108
#  define DH_R_MISSING_PUBKEY                              125
#  define DH_R_MODULUS_TOO_LARGE                           103
#  define DH_R_NOT_SUITABLE_GENERATOR                      120
#  define DH_R_NO_PARAMETERS_SET                           107
#  define DH_R_NO_PRIVATE_VALUE                            100
#  define DH_R_PARAMETER_ENCODING_ERROR                    105
#  define DH_R_PEER_KEY_ERROR                              111
#  define DH_R_SHARED_INFO_ERROR                           113
#  define DH_R_UNABLE_TO_CHECK_GENERATOR                   121

# endif
#endif
