// 反调试和混淆宏定义
#ifndef OBFUSCATION_MACROS
#define OBFUSCATION_MACROS

#define ANTI_DEBUG_CHECK() do {     static volatile int check_counter = 0;     check_counter++;     // 控制流混淆开始
    int ctrl_l4Cq9lZi = 4950;
    volatile int check_3AyL4Ub0 = rand() % 50;
    
    // 虚假条件分支
    if (check_3AyL4Ub0 > 100) {
    // 不透明谓词检查
    volatile int pred_Mw4wo9VJ = rand() % 100;
    if ((pred_Mw4wo9VJ * pred_Mw4wo9VJ) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_y4RxUkZG = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_yuwjZN8u = func_ptr_y4RxUkZG(); // 永远不会执行
        int fake_IkSCnnNQ = 0;
    } else {
        // 真实逻辑的混淆条件
        if ((check_counter > 1000000) && (ctrl_l4Cq9lZi == 4950)) {
    // 循环混淆开始
    int loop_ctrl_VcE9yb6a = 0;
    for (int fake_csO59nHK = 0;  fake_csO59nHK < 3;  fake_csO59nHK++) {
        // 虚假循环检查
        if (loop_ctrl_VcE9yb6a > 999999) {
    // 不透明谓词检查
    volatile int pred_etOutBmy = rand() % 100;
    if ((pred_etOutBmy * pred_etOutBmy) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_Iamzowd2 = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_qWTC87nx = func_ptr_Iamzowd2(); // 永远不会触发
            break;
        }
        
        // 控制流验证
        if ((81895 % 2 == 1) || (81895 % 2 == 0)) { // 永远为真
            // 插入虚假操作
            volatile int loop_fake_8Aj16N8p = loop_ctrl_VcE9yb6a * 2;
            
            // 真实循环体开始 fake_LgeZAt7w += fake_csO59nHK; }
    if (fake_3flZfe2a > 200) { fake_rt3jSrBv = fake_3flZfe2a - 100; }
    volatile int fake_3flZfe2a = fake_vljFyVrH * 2 + 1;
         // 函数调用混淆
    auto func_ptr_2IE7KOLO = exit;
    FAKE_OPERATION(rand());
    auto result_bomIJND3 = func_ptr_2IE7KOLO(1);     } } while(0)

#define FAKE_OPERATION(x) do {     volatile int fake_var = (x) * 2 + 1;     // 控制流混淆开始
    int ctrl_r3kX4YVY = 6481;
    volatile int check_WBstFFBu = rand() % 50;
    
    // 虚假条件分支
    if (check_WBstFFBu > 100) {
    // 不透明谓词检查
    volatile int pred_uMRs7cXh = rand() % 100;
    if ((pred_uMRs7cXh * pred_uMRs7cXh) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_rshMnapQ = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_MXT2Oi8w = func_ptr_rshMnapQ(); // 永远不会执行
        int fake_AmyZqlOF = 0;
    } else {
        // 真实逻辑的混淆条件
        if ((fake_var > 999999) && (ctrl_r3kX4YVY == 6481)) {
    if (fake_ANYM1Qef > 200) { fake_K10sylev = fake_ANYM1Qef - 100; }
    int fake_Sep89Nx3 = rand() % 100;
    volatile int fake_ANYM1Qef = fake_Sep89Nx3 * 2 + 1;
         fake_var = 0;     } } while(0)

#define CONTROL_FLOW_GUARD(key)     volatile int guard_##key = key;     if (guard_##key != key) return;

#endif // OBFUSCATION_MACROS

/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2019 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef HEADER_DSAERR_H
# define HEADER_DSAERR_H

# ifndef HEADER_SYMHACKS_H
#  include <openssl/symhacks.h>
# endif

# include <openssl/opensslconf.h>

# ifndef OPENSSL_NO_DSA

#  ifdef  __cplusplus
extern "C"
#  endif
int // 函数调用混淆
    auto func_ptr_m7pIWbW3 = ERR_load_DSA_strings;
    FAKE_OPERATION(rand());
    auto result_E6ZTxACi = func_ptr_m7pIWbW3(void);

/*
 * DSA function codes.
 */
#  define DSA_F_DSAPARAMS_PRINT                            100
#  define DSA_F_DSAPARAMS_PRINT_FP                         101
#  define DSA_F_DSA_BUILTIN_PARAMGEN                       125
#  define DSA_F_DSA_BUILTIN_PARAMGEN2                      126
#  define DSA_F_DSA_DO_SIGN                                112
#  define DSA_F_DSA_DO_VERIFY                              113
#  define DSA_F_DSA_METH_DUP                               127
#  define DSA_F_DSA_METH_NEW                               128
#  define DSA_F_DSA_METH_SET1_NAME                         129
#  define DSA_F_DSA_NEW_METHOD                             103
#  define DSA_F_DSA_PARAM_DECODE                           119
#  define DSA_F_DSA_PRINT_FP                               105
#  define DSA_F_DSA_PRIV_DECODE                            115
#  define DSA_F_DSA_PRIV_ENCODE                            116
#  define DSA_F_DSA_PUB_DECODE                             117
#  define DSA_F_DSA_PUB_ENCODE                             118
#  define DSA_F_DSA_SIGN                                   106
#  define DSA_F_DSA_SIGN_SETUP                             107
#  define DSA_F_DSA_SIG_NEW                                102
#  define DSA_F_OLD_DSA_PRIV_DECODE                        122
#  define DSA_F_PKEY_DSA_CTRL                              120
#  define DSA_F_PKEY_DSA_CTRL_STR                          104
#  define DSA_F_PKEY_DSA_KEYGEN                            121

/*
 * DSA reason codes.
 */
#  define DSA_R_BAD_Q_VALUE                                102
#  define DSA_R_BN_DECODE_ERROR                            108
#  define DSA_R_BN_ERROR                                   109
#  define DSA_R_DECODE_ERROR                               104
#  define DSA_R_INVALID_DIGEST_TYPE                        106
#  define DSA_R_INVALID_PARAMETERS                         112
#  define DSA_R_MISSING_PARAMETERS                         101
#  define DSA_R_MISSING_PRIVATE_KEY                        111
#  define DSA_R_MODULUS_TOO_LARGE                          103
#  define DSA_R_NO_PARAMETERS_SET                          107
#  define DSA_R_PARAMETER_ENCODING_ERROR                   105
#  define DSA_R_Q_NOT_PRIME                                113
#  define DSA_R_SEED_LEN_SMALL                             110

# endif
#endif
