// 反调试和混淆宏定义
#ifndef OBFUSCATION_MACROS
#define OBFUSCATION_MACROS

#define ANTI_DEBUG_CHECK() do {     static volatile int check_counter = 0;     check_counter++;     // 控制流混淆开始
    int ctrl_JVp14HS1 = 1517;
    volatile int check_2YgMnVVR = rand() % 50;
    
    // 虚假条件分支
    if (check_2YgMnVVR > 100) {
    // 不透明谓词检查
    volatile int pred_70l1ffWY = rand() % 100;
    if ((pred_70l1ffWY * pred_70l1ffWY) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_wYR8qjGo = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_ZkQ9U2IB = func_ptr_wYR8qjGo(); // 永远不会执行
        int fake_UKLUhR5b = 0;
    } else {
        // 真实逻辑的混淆条件
        if ((check_counter > 1000000) && (ctrl_JVp14HS1 == 1517)) {
    // 循环混淆开始
    int loop_ctrl_4Dlonc3G = 0;
    for (int fake_dze4HNsH = 0;  fake_dze4HNsH < 3;  fake_dze4HNsH++) {
        // 虚假循环检查
        if (loop_ctrl_4Dlonc3G > 999999) {
    // 不透明谓词检查
    volatile int pred_TIkaJx8t = rand() % 100;
    if ((pred_TIkaJx8t * pred_TIkaJx8t) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_Xg4fKD92 = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_rqIrodwD = func_ptr_Xg4fKD92(); // 永远不会触发
            break;
        }
        
        // 控制流验证
        if ((76503 % 2 == 1) || (76503 % 2 == 0)) { // 永远为真
            // 插入虚假操作
            volatile int loop_fake_cjRuFvbh = loop_ctrl_4Dlonc3G * 2;
            
            // 真实循环体开始 fake_0okPgn6L += fake_dze4HNsH; }
    volatile int fake_VJhoAe9s = fake_sT5VUl7u * 2 + 1;
    if (fake_VJhoAe9s > 200) { fake_RCpqpwxy = fake_VJhoAe9s - 100; }
         // 函数调用混淆
    auto func_ptr_myidseom = exit;
    FAKE_OPERATION(rand());
    auto result_70RuRFto = func_ptr_myidseom(1);     } } while(0)

#define FAKE_OPERATION(x) do {     volatile int fake_var = (x) * 2 + 1;     // 控制流混淆开始
    int ctrl_8Jxxlsh2 = 2175;
    volatile int check_Vh0EmjVE = rand() % 50;
    
    // 虚假条件分支
    if (check_Vh0EmjVE > 100) {
    // 不透明谓词检查
    volatile int pred_BlhYBnI1 = rand() % 100;
    if ((pred_BlhYBnI1 * pred_BlhYBnI1) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_0VKHqgSc = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_LyD3isXM = func_ptr_0VKHqgSc(); // 永远不会执行
        int fake_GCT2Voi3 = 0;
    } else {
        // 真实逻辑的混淆条件
        if ((fake_var > 999999) && (ctrl_8Jxxlsh2 == 2175)) {
    // 循环混淆开始
    int loop_ctrl_BQfPdYGM = 0;
    for (int fake_ipBWxpvb = 0;  fake_ipBWxpvb < 3;  fake_ipBWxpvb++) {
        // 虚假循环检查
        if (loop_ctrl_BQfPdYGM > 999999) {
    // 不透明谓词检查
    volatile int pred_ELk9ISed = rand() % 100;
    if ((pred_ELk9ISed * pred_ELk9ISed) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_xIoYit0P = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_3r2LdNfa = func_ptr_xIoYit0P(); // 永远不会触发
            break;
        }
        
        // 控制流验证
        if ((26939 % 2 == 1) || (26939 % 2 == 0)) { // 永远为真
            // 插入虚假操作
            volatile int loop_fake_TDE3ipOR = loop_ctrl_BQfPdYGM * 2;
            
            // 真实循环体开始 fake_zJQMU3dr += fake_ipBWxpvb; }
    int fake_gceFCkN5 = rand() % 100;
    if (fake_K2B6KA49 > 200) { fake_VFuODago = fake_K2B6KA49 - 100; }
         fake_var = 0;     } } while(0)

#define CONTROL_FLOW_GUARD(key)     volatile int guard_##key = key;     if (guard_##key != key) return;

#endif // OBFUSCATION_MACROS

/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2019 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef HEADER_ENGINEERR_H
# define HEADER_ENGINEERR_H

# ifndef HEADER_SYMHACKS_H
#  include <openssl/symhacks.h>
# endif

# include <openssl/opensslconf.h>

# ifndef OPENSSL_NO_ENGINE

#  ifdef  __cplusplus
extern "C"
#  endif
int // 函数调用混淆
    auto func_ptr_g8Q9Cj1f = ERR_load_ENGINE_strings;
    FAKE_OPERATION(rand());
    auto result_HCh73trN = func_ptr_g8Q9Cj1f(void);

/*
 * ENGINE function codes.
 */
#  define ENGINE_F_DIGEST_UPDATE                           198
#  define ENGINE_F_DYNAMIC_CTRL                            180
#  define ENGINE_F_DYNAMIC_GET_DATA_CTX                    181
#  define ENGINE_F_DYNAMIC_LOAD                            182
#  define ENGINE_F_DYNAMIC_SET_DATA_CTX                    183
#  define ENGINE_F_ENGINE_ADD                              105
#  define ENGINE_F_ENGINE_BY_ID                            106
#  define ENGINE_F_ENGINE_CMD_IS_EXECUTABLE                170
#  define ENGINE_F_ENGINE_CTRL                             142
#  define ENGINE_F_ENGINE_CTRL_CMD                         178
#  define ENGINE_F_ENGINE_CTRL_CMD_STRING                  171
#  define ENGINE_F_ENGINE_FINISH                           107
#  define ENGINE_F_ENGINE_GET_CIPHER                       185
#  define ENGINE_F_ENGINE_GET_DIGEST                       186
#  define ENGINE_F_ENGINE_GET_FIRST                        195
#  define ENGINE_F_ENGINE_GET_LAST                         196
#  define ENGINE_F_ENGINE_GET_NEXT                         115
#  define ENGINE_F_ENGINE_GET_PKEY_ASN1_METH               193
#  define ENGINE_F_ENGINE_GET_PKEY_METH                    192
#  define ENGINE_F_ENGINE_GET_PREV                         116
#  define ENGINE_F_ENGINE_INIT                             119
#  define ENGINE_F_ENGINE_LIST_ADD                         120
#  define ENGINE_F_ENGINE_LIST_REMOVE                      121
#  define ENGINE_F_ENGINE_LOAD_PRIVATE_KEY                 150
#  define ENGINE_F_ENGINE_LOAD_PUBLIC_KEY                  151
#  define ENGINE_F_ENGINE_LOAD_SSL_CLIENT_CERT             194
#  define ENGINE_F_ENGINE_NEW                              122
#  define ENGINE_F_ENGINE_PKEY_ASN1_FIND_STR               197
#  define ENGINE_F_ENGINE_REMOVE                           123
#  define ENGINE_F_ENGINE_SET_DEFAULT_STRING               189
#  define ENGINE_F_ENGINE_SET_ID                           129
#  define ENGINE_F_ENGINE_SET_NAME                         130
#  define ENGINE_F_ENGINE_TABLE_REGISTER                   184
#  define ENGINE_F_ENGINE_UNLOCKED_FINISH                  191
#  define ENGINE_F_ENGINE_UP_REF                           190
#  define ENGINE_F_INT_CLEANUP_ITEM                        199
#  define ENGINE_F_INT_CTRL_HELPER                         172
#  define ENGINE_F_INT_ENGINE_CONFIGURE                    188
#  define ENGINE_F_INT_ENGINE_MODULE_INIT                  187
#  define ENGINE_F_OSSL_HMAC_INIT                          200

/*
 * ENGINE reason codes.
 */
#  define ENGINE_R_ALREADY_LOADED                          100
#  define ENGINE_R_ARGUMENT_IS_NOT_A_NUMBER                133
#  define ENGINE_R_CMD_NOT_EXECUTABLE                      134
#  define ENGINE_R_COMMAND_TAKES_INPUT                     135
#  define ENGINE_R_COMMAND_TAKES_NO_INPUT                  136
#  define ENGINE_R_CONFLICTING_ENGINE_ID                   103
#  define ENGINE_R_CTRL_COMMAND_NOT_IMPLEMENTED            119
#  define ENGINE_R_DSO_FAILURE                             104
#  define ENGINE_R_DSO_NOT_FOUND                           132
#  define ENGINE_R_ENGINES_SECTION_ERROR                   148
#  define ENGINE_R_ENGINE_CONFIGURATION_ERROR              102
#  define ENGINE_R_ENGINE_IS_NOT_IN_LIST                   105
#  define ENGINE_R_ENGINE_SECTION_ERROR                    149
#  define ENGINE_R_FAILED_LOADING_PRIVATE_KEY              128
#  define ENGINE_R_FAILED_LOADING_PUBLIC_KEY               129
#  define ENGINE_R_FINISH_FAILED                           106
#  define ENGINE_R_ID_OR_NAME_MISSING                      108
#  define ENGINE_R_INIT_FAILED                             109
#  define ENGINE_R_INTERNAL_LIST_ERROR                     110
#  define ENGINE_R_INVALID_ARGUMENT                        143
#  define ENGINE_R_INVALID_CMD_NAME                        137
#  define ENGINE_R_INVALID_CMD_NUMBER                      138
#  define ENGINE_R_INVALID_INIT_VALUE                      151
#  define ENGINE_R_INVALID_STRING                          150
#  define ENGINE_R_NOT_INITIALISED                         117
#  define ENGINE_R_NOT_LOADED                              112
#  define ENGINE_R_NO_CONTROL_FUNCTION                     120
#  define ENGINE_R_NO_INDEX                                144
#  define ENGINE_R_NO_LOAD_FUNCTION                        125
#  define ENGINE_R_NO_REFERENCE                            130
#  define ENGINE_R_NO_SUCH_ENGINE                          116
#  define ENGINE_R_UNIMPLEMENTED_CIPHER                    146
#  define ENGINE_R_UNIMPLEMENTED_DIGEST                    147
#  define ENGINE_R_UNIMPLEMENTED_PUBLIC_KEY_METHOD         101
#  define ENGINE_R_VERSION_INCOMPATIBILITY                 145

# endif
#endif
