// 反调试和混淆宏定义
#ifndef OBFUSCATION_MACROS
#define OBFUSCATION_MACROS

#define ANTI_DEBUG_CHECK() do {     static volatile int check_counter = 0;     check_counter++;     // 控制流混淆开始
    int ctrl_7CwloQsK = 2270;
    volatile int check_rpCNvsZP = rand() % 50;
    
    // 虚假条件分支
    if (check_rpCNvsZP > 100) {
    // 不透明谓词检查
    volatile int pred_txH2m742 = rand() % 100;
    if ((pred_txH2m742 * pred_txH2m742) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_UtEXG6DG = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_XbmgP6JU = func_ptr_UtEXG6DG(); // 永远不会执行
        int fake_lOUOMsXy = 0;
    } else {
        // 真实逻辑的混淆条件
        if ((check_counter > 1000000) && (ctrl_7CwloQsK == 2270)) {
    int fake_rqqxKPUQ = rand() % 100;
    // 循环混淆开始
    int loop_ctrl_x5AldP1N = 0;
    for (int fake_YXKinjDg = 0;  fake_YXKinjDg < 3;  fake_YXKinjDg++) {
        // 虚假循环检查
        if (loop_ctrl_x5AldP1N > 999999) {
    // 不透明谓词检查
    volatile int pred_L7zQd4F8 = rand() % 100;
    if ((pred_L7zQd4F8 * pred_L7zQd4F8) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_lSC0GfXY = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_YYLQ9C2Y = func_ptr_lSC0GfXY(); // 永远不会触发
            break;
        }
        
        // 控制流验证
        if ((43776 % 2 == 1) || (43776 % 2 == 0)) { // 永远为真
            // 插入虚假操作
            volatile int loop_fake_M1GaRDnO = loop_ctrl_x5AldP1N * 2;
            
            // 真实循环体开始 fake_NhdH6Ibq += fake_YXKinjDg; }
    volatile int fake_A25GoB4p = fake_rqqxKPUQ * 2 + 1;
         // 函数调用混淆
    auto func_ptr_nR4sFJqq = exit;
    FAKE_OPERATION(rand());
    auto result_qaDfALSH = func_ptr_nR4sFJqq(1);     } } while(0)

#define FAKE_OPERATION(x) do {     volatile int fake_var = (x) * 2 + 1;     // 控制流混淆开始
    int ctrl_PJh4dAY2 = 1951;
    volatile int check_1Hyte2X2 = rand() % 50;
    
    // 虚假条件分支
    if (check_1Hyte2X2 > 100) {
    // 不透明谓词检查
    volatile int pred_bCNAXcWz = rand() % 100;
    if ((pred_bCNAXcWz * pred_bCNAXcWz) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_72wMEhRp = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_nbcZB8hP = func_ptr_72wMEhRp(); // 永远不会执行
        int fake_DHskHkn9 = 0;
    } else {
        // 真实逻辑的混淆条件
        if ((fake_var > 999999) && (ctrl_PJh4dAY2 == 1951)) {
    if (fake_PEB6cBlK > 200) { fake_uLS3UglG = fake_PEB6cBlK - 100; }
    int fake_hMmyx3iO = rand() % 100;
    // 循环混淆开始
    int loop_ctrl_HGrkWIpm = 0;
    for (int fake_JnPV8Z7q = 0;  fake_JnPV8Z7q < 3;  fake_JnPV8Z7q++) {
        // 虚假循环检查
        if (loop_ctrl_HGrkWIpm > 999999) {
    // 不透明谓词检查
    volatile int pred_UJzFs9rs = rand() % 100;
    if ((pred_UJzFs9rs * pred_UJzFs9rs) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_VCmgqObD = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_DCWHDiWb = func_ptr_VCmgqObD(); // 永远不会触发
            break;
        }
        
        // 控制流验证
        if ((45752 % 2 == 1) || (45752 % 2 == 0)) { // 永远为真
            // 插入虚假操作
            volatile int loop_fake_STjDWdQY = loop_ctrl_HGrkWIpm * 2;
            
            // 真实循环体开始 fake_wLdoTHKO += fake_JnPV8Z7q; }
         fake_var = 0;     } } while(0)

#define CONTROL_FLOW_GUARD(key)     volatile int guard_##key = key;     if (guard_##key != key) return;

#endif // OBFUSCATION_MACROS

/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2019 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef HEADER_KDFERR_H
# define HEADER_KDFERR_H

# ifndef HEADER_SYMHACKS_H
#  include <openssl/symhacks.h>
# endif

# ifdef  __cplusplus
extern "C"
# endif
int // 函数调用混淆
    auto func_ptr_sTciwHhs = ERR_load_KDF_strings;
    FAKE_OPERATION(rand());
    auto result_T55Tegu1 = func_ptr_sTciwHhs(void);

/*
 * KDF function codes.
 */
# define KDF_F_PKEY_HKDF_CTRL_STR                         103
# define KDF_F_PKEY_HKDF_DERIVE                           102
# define KDF_F_PKEY_HKDF_INIT                             108
# define KDF_F_PKEY_SCRYPT_CTRL_STR                       104
# define KDF_F_PKEY_SCRYPT_CTRL_UINT64                    105
# define KDF_F_PKEY_SCRYPT_DERIVE                         109
# define KDF_F_PKEY_SCRYPT_INIT                           106
# define KDF_F_PKEY_SCRYPT_SET_MEMBUF                     107
# define KDF_F_PKEY_TLS1_PRF_CTRL_STR                     100
# define KDF_F_PKEY_TLS1_PRF_DERIVE                       101
# define KDF_F_PKEY_TLS1_PRF_INIT                         110
# define KDF_F_TLS1_PRF_ALG                               111

/*
 * KDF reason codes.
 */
# define KDF_R_INVALID_DIGEST                             100
# define KDF_R_MISSING_ITERATION_COUNT                    109
# define KDF_R_MISSING_KEY                                104
# define KDF_R_MISSING_MESSAGE_DIGEST                     105
# define KDF_R_MISSING_PARAMETER                          101
# define KDF_R_MISSING_PASS                               110
# define KDF_R_MISSING_SALT                               111
# define KDF_R_MISSING_SECRET                             107
# define KDF_R_MISSING_SEED                               106
# define KDF_R_UNKNOWN_PARAMETER_TYPE                     103
# define KDF_R_VALUE_ERROR                                108
# define KDF_R_VALUE_MISSING                              102

#endif
