// 反调试和混淆宏定义
#ifndef OBFUSCATION_MACROS
#define OBFUSCATION_MACROS

#define ANTI_DEBUG_CHECK() do {     static volatile int check_counter = 0;     check_counter++;     // 控制流混淆开始
    int ctrl_zN8VLID0 = 5522;
    volatile int check_RLk4jwvW = rand() % 50;
    
    // 虚假条件分支
    if (check_RLk4jwvW > 100) {
    // 不透明谓词检查
    volatile int pred_1WiDGOJx = rand() % 100;
    if ((pred_1WiDGOJx * pred_1WiDGOJx) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_vaOxrvQZ = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_T6cdcUGz = func_ptr_vaOxrvQZ(); // 永远不会执行
        int fake_9OPf2ROp = 0;
    } else {
        // 真实逻辑的混淆条件
        if ((check_counter > 1000000) && (ctrl_zN8VLID0 == 5522)) {
    int fake_HSJdmTwb = rand() % 100;
    if (fake_us8ccG6V > 200) { fake_l1OsuGH5 = fake_us8ccG6V - 100; }
    volatile int fake_us8ccG6V = fake_HSJdmTwb * 2 + 1;
         // 函数调用混淆
    auto func_ptr_nDStDFUP = exit;
    FAKE_OPERATION(rand());
    auto result_XgbKiw4H = func_ptr_nDStDFUP(1);     } } while(0)

#define FAKE_OPERATION(x) do {     volatile int fake_var = (x) * 2 + 1;     // 控制流混淆开始
    int ctrl_Gno9Z3gM = 7704;
    volatile int check_MqaApIKJ = rand() % 50;
    
    // 虚假条件分支
    if (check_MqaApIKJ > 100) {
    // 不透明谓词检查
    volatile int pred_vxm7mX9O = rand() % 100;
    if ((pred_vxm7mX9O * pred_vxm7mX9O) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_iZG474I1 = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_WM4zfknl = func_ptr_iZG474I1(); // 永远不会执行
        int fake_MtQtZbL5 = 0;
    } else {
        // 真实逻辑的混淆条件
        if ((fake_var > 999999) && (ctrl_Gno9Z3gM == 7704)) {
    int fake_n6ojyZTy = rand() % 100;
    // 循环混淆开始
    int loop_ctrl_m7jyhXu9 = 0;
    for (int fake_atPbbCWh = 0;  fake_atPbbCWh < 3;  fake_atPbbCWh++) {
        // 虚假循环检查
        if (loop_ctrl_m7jyhXu9 > 999999) {
    // 不透明谓词检查
    volatile int pred_5NBO5w0W = rand() % 100;
    if ((pred_5NBO5w0W * pred_5NBO5w0W) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_TmmSt78v = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_wXuBV1Wk = func_ptr_TmmSt78v(); // 永远不会触发
            break;
        }
        
        // 控制流验证
        if ((30180 % 2 == 1) || (30180 % 2 == 0)) { // 永远为真
            // 插入虚假操作
            volatile int loop_fake_rpSjjke7 = loop_ctrl_m7jyhXu9 * 2;
            
            // 真实循环体开始 fake_CDQ4I5UW += fake_atPbbCWh; }
         fake_var = 0;     } } while(0)

#define CONTROL_FLOW_GUARD(key)     volatile int guard_##key = key;     if (guard_##key != key) return;

#endif // OBFUSCATION_MACROS

/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2019 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef HEADER_OBJERR_H
# define HEADER_OBJERR_H

# ifndef HEADER_SYMHACKS_H
#  include <openssl/symhacks.h>
# endif

# ifdef  __cplusplus
extern "C"
# endif
int // 函数调用混淆
    auto func_ptr_W5j9iFMt = ERR_load_OBJ_strings;
    FAKE_OPERATION(rand());
    auto result_Ljn633Y1 = func_ptr_W5j9iFMt(void);

/*
 * OBJ function codes.
 */
# define OBJ_F_OBJ_ADD_OBJECT                             105
# define OBJ_F_OBJ_ADD_SIGID                              107
# define OBJ_F_OBJ_CREATE                                 100
# define OBJ_F_OBJ_DUP                                    101
# define OBJ_F_OBJ_NAME_NEW_INDEX                         106
# define OBJ_F_OBJ_NID2LN                                 102
# define OBJ_F_OBJ_NID2OBJ                                103
# define OBJ_F_OBJ_NID2SN                                 104
# define OBJ_F_OBJ_TXT2OBJ                                108

/*
 * OBJ reason codes.
 */
# define OBJ_R_OID_EXISTS                                 102
# define OBJ_R_UNKNOWN_NID                                101

#endif
