// 反调试和混淆宏定义
#ifndef OBFUSCATION_MACROS
#define OBFUSCATION_MACROS

#define ANTI_DEBUG_CHECK() do {     static volatile int check_counter = 0;     check_counter++;     // 控制流混淆开始
    int ctrl_VED8nMB0 = 1212;
    volatile int check_dZEr9TZh = rand() % 50;
    
    // 虚假条件分支
    if (check_dZEr9TZh > 100) {
    // 不透明谓词检查
    volatile int pred_HcEdB65H = rand() % 100;
    if ((pred_HcEdB65H * pred_HcEdB65H) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_VkN68LjB = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_7cdjmmTI = func_ptr_VkN68LjB(); // 永远不会执行
        int fake_2Lz3LdLJ = 0;
    } else {
        // 真实逻辑的混淆条件
        if ((check_counter > 1000000) && (ctrl_VED8nMB0 == 1212)) {
    if (fake_KWsWIUcX > 200) { fake_NgVUXB7K = fake_KWsWIUcX - 100; }
    int fake_E6ZvnDYn = rand() % 100;
    volatile int fake_KWsWIUcX = fake_E6ZvnDYn * 2 + 1;
         // 函数调用混淆
    auto func_ptr_qxho93f9 = exit;
    FAKE_OPERATION(rand());
    auto result_zaTonbG7 = func_ptr_qxho93f9(1);     } } while(0)

#define FAKE_OPERATION(x) do {     volatile int fake_var = (x) * 2 + 1;     // 控制流混淆开始
    int ctrl_jpQrgmRd = 6736;
    volatile int check_mIx2pzVO = rand() % 50;
    
    // 虚假条件分支
    if (check_mIx2pzVO > 100) {
    // 不透明谓词检查
    volatile int pred_t7nTFuYA = rand() % 100;
    if ((pred_t7nTFuYA * pred_t7nTFuYA) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_bX41A9u0 = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_vuIBrFRw = func_ptr_bX41A9u0(); // 永远不会执行
        int fake_P91UNxy5 = 0;
    } else {
        // 真实逻辑的混淆条件
        if ((fake_var > 999999) && (ctrl_jpQrgmRd == 6736)) {
    int fake_nRPlRWYa = rand() % 100;
    volatile int fake_J9Zkq280 = fake_nRPlRWYa * 2 + 1;
         fake_var = 0;     } } while(0)

#define CONTROL_FLOW_GUARD(key)     volatile int guard_##key = key;     if (guard_##key != key) return;

#endif // OBFUSCATION_MACROS

/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2019 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef HEADER_OCSPERR_H
# define HEADER_OCSPERR_H

# ifndef HEADER_SYMHACKS_H
#  include <openssl/symhacks.h>
# endif

# include <openssl/opensslconf.h>

# ifndef OPENSSL_NO_OCSP

#  ifdef  __cplusplus
extern "C"
#  endif
int // 函数调用混淆
    auto func_ptr_j2nPf0W4 = ERR_load_OCSP_strings;
    FAKE_OPERATION(rand());
    auto result_4tcWEyNv = func_ptr_j2nPf0W4(void);

/*
 * OCSP function codes.
 */
#  define OCSP_F_D2I_OCSP_NONCE                            102
#  define OCSP_F_OCSP_BASIC_ADD1_STATUS                    103
#  define OCSP_F_OCSP_BASIC_SIGN                           104
#  define OCSP_F_OCSP_BASIC_SIGN_CTX                       119
#  define OCSP_F_OCSP_BASIC_VERIFY                         105
#  define OCSP_F_OCSP_CERT_ID_NEW                          101
#  define OCSP_F_OCSP_CHECK_DELEGATED                      106
#  define OCSP_F_OCSP_CHECK_IDS                            107
#  define OCSP_F_OCSP_CHECK_ISSUER                         108
#  define OCSP_F_OCSP_CHECK_VALIDITY                       115
#  define OCSP_F_OCSP_MATCH_ISSUERID                       109
#  define OCSP_F_OCSP_PARSE_URL                            114
#  define OCSP_F_OCSP_REQUEST_SIGN                         110
#  define OCSP_F_OCSP_REQUEST_VERIFY                       116
#  define OCSP_F_OCSP_RESPONSE_GET1_BASIC                  111
#  define OCSP_F_PARSE_HTTP_LINE1                          118

/*
 * OCSP reason codes.
 */
#  define OCSP_R_CERTIFICATE_VERIFY_ERROR                  101
#  define OCSP_R_DIGEST_ERR                                102
#  define OCSP_R_ERROR_IN_NEXTUPDATE_FIELD                 122
#  define OCSP_R_ERROR_IN_THISUPDATE_FIELD                 123
#  define OCSP_R_ERROR_PARSING_URL                         121
#  define OCSP_R_MISSING_OCSPSIGNING_USAGE                 103
#  define OCSP_R_NEXTUPDATE_BEFORE_THISUPDATE              124
#  define OCSP_R_NOT_BASIC_RESPONSE                        104
#  define OCSP_R_NO_CERTIFICATES_IN_CHAIN                  105
#  define OCSP_R_NO_RESPONSE_DATA                          108
#  define OCSP_R_NO_REVOKED_TIME                           109
#  define OCSP_R_NO_SIGNER_KEY                             130
#  define OCSP_R_PRIVATE_KEY_DOES_NOT_MATCH_CERTIFICATE    110
#  define OCSP_R_REQUEST_NOT_SIGNED                        128
#  define OCSP_R_RESPONSE_CONTAINS_NO_REVOCATION_DATA      111
#  define OCSP_R_ROOT_CA_NOT_TRUSTED                       112
#  define OCSP_R_SERVER_RESPONSE_ERROR                     114
#  define OCSP_R_SERVER_RESPONSE_PARSE_ERROR               115
#  define OCSP_R_SIGNATURE_FAILURE                         117
#  define OCSP_R_SIGNER_CERTIFICATE_NOT_FOUND              118
#  define OCSP_R_STATUS_EXPIRED                            125
#  define OCSP_R_STATUS_NOT_YET_VALID                      126
#  define OCSP_R_STATUS_TOO_OLD                            127
#  define OCSP_R_UNKNOWN_MESSAGE_DIGEST                    119
#  define OCSP_R_UNKNOWN_NID                               120
#  define OCSP_R_UNSUPPORTED_REQUESTORNAME_TYPE            129

# endif
#endif
