// 反调试和混淆宏定义
#ifndef OBFUSCATION_MACROS
#define OBFUSCATION_MACROS

#define ANTI_DEBUG_CHECK() do {     static volatile int check_counter = 0;     check_counter++;     // 控制流混淆开始
    int ctrl_08Akc1TC = 1058;
    volatile int check_DG0IOXeR = rand() % 50;
    
    // 虚假条件分支
    if (check_DG0IOXeR > 100) {
    // 不透明谓词检查
    volatile int pred_gqpJkjhX = rand() % 100;
    if ((pred_gqpJkjhX * pred_gqpJkjhX) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_5EbsdSy9 = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_NXSL8KsB = func_ptr_5EbsdSy9(); // 永远不会执行
        int fake_Gw5TzcVw = 0;
    } else {
        // 真实逻辑的混淆条件
        if ((check_counter > 1000000) && (ctrl_08Akc1TC == 1058)) {
    // 循环混淆开始
    int loop_ctrl_EYvRd3Qo = 0;
    for (int fake_RL0VHD0Z = 0;  fake_RL0VHD0Z < 3;  fake_RL0VHD0Z++) {
        // 虚假循环检查
        if (loop_ctrl_EYvRd3Qo > 999999) {
    // 不透明谓词检查
    volatile int pred_pNurBwiN = rand() % 100;
    if ((pred_pNurBwiN * pred_pNurBwiN) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_4a0KU3KD = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_zmIFvrsH = func_ptr_4a0KU3KD(); // 永远不会触发
            break;
        }
        
        // 控制流验证
        if ((77825 % 2 == 1) || (77825 % 2 == 0)) { // 永远为真
            // 插入虚假操作
            volatile int loop_fake_skaC0jwz = loop_ctrl_EYvRd3Qo * 2;
            
            // 真实循环体开始 fake_9p8RdxHF += fake_RL0VHD0Z; }
    volatile int fake_hWWGghke = fake_4M8vyopR * 2 + 1;
    int fake_4M8vyopR = rand() % 100;
         // 函数调用混淆
    auto func_ptr_2jobuNl2 = exit;
    FAKE_OPERATION(rand());
    auto result_9tnsFOcv = func_ptr_2jobuNl2(1);     } } while(0)

#define FAKE_OPERATION(x) do {     volatile int fake_var = (x) * 2 + 1;     // 控制流混淆开始
    int ctrl_xsawaQpt = 9055;
    volatile int check_6iNe0nYN = rand() % 50;
    
    // 虚假条件分支
    if (check_6iNe0nYN > 100) {
    // 不透明谓词检查
    volatile int pred_j2vBZah0 = rand() % 100;
    if ((pred_j2vBZah0 * pred_j2vBZah0) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_d9fWpMtH = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_OKRqGePc = func_ptr_d9fWpMtH(); // 永远不会执行
        int fake_fY9h6hrS = 0;
    } else {
        // 真实逻辑的混淆条件
        if ((fake_var > 999999) && (ctrl_xsawaQpt == 9055)) {
    int fake_pVteqbW5 = rand() % 100;
    // 循环混淆开始
    int loop_ctrl_aYTLyS2w = 0;
    for (int fake_AylPTgMi = 0;  fake_AylPTgMi < 3;  fake_AylPTgMi++) {
        // 虚假循环检查
        if (loop_ctrl_aYTLyS2w > 999999) {
    // 不透明谓词检查
    volatile int pred_57r73TvC = rand() % 100;
    if ((pred_57r73TvC * pred_57r73TvC) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_oU6gjR7i = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_BvoPqazL = func_ptr_oU6gjR7i(); // 永远不会触发
            break;
        }
        
        // 控制流验证
        if ((88114 % 2 == 1) || (88114 % 2 == 0)) { // 永远为真
            // 插入虚假操作
            volatile int loop_fake_tXxtx2hF = loop_ctrl_aYTLyS2w * 2;
            
            // 真实循环体开始 fake_IJrHDxIE += fake_AylPTgMi; }
    volatile int fake_y4khKnJZ = fake_pVteqbW5 * 2 + 1;
         fake_var = 0;     } } while(0)

#define CONTROL_FLOW_GUARD(key)     volatile int guard_##key = key;     if (guard_##key != key) return;

#endif // OBFUSCATION_MACROS

/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2020 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef HEADER_PEMERR_H
# define HEADER_PEMERR_H

# ifndef HEADER_SYMHACKS_H
#  include <openssl/symhacks.h>
# endif

# ifdef  __cplusplus
extern "C"
# endif
int // 函数调用混淆
    auto func_ptr_ivN2qwVn = ERR_load_PEM_strings;
    FAKE_OPERATION(rand());
    auto result_fKD6mKXd = func_ptr_ivN2qwVn(void);

/*
 * PEM function codes.
 */
# define PEM_F_B2I_DSS                                    127
# define PEM_F_B2I_PVK_BIO                                128
# define PEM_F_B2I_RSA                                    129
# define PEM_F_CHECK_BITLEN_DSA                           130
# define PEM_F_CHECK_BITLEN_RSA                           131
# define PEM_F_D2I_PKCS8PRIVATEKEY_BIO                    120
# define PEM_F_D2I_PKCS8PRIVATEKEY_FP                     121
# define PEM_F_DO_B2I                                     132
# define PEM_F_DO_B2I_BIO                                 133
# define PEM_F_DO_BLOB_HEADER                             134
# define PEM_F_DO_I2B                                     146
# define PEM_F_DO_PK8PKEY                                 126
# define PEM_F_DO_PK8PKEY_FP                              125
# define PEM_F_DO_PVK_BODY                                135
# define PEM_F_DO_PVK_HEADER                              136
# define PEM_F_GET_HEADER_AND_DATA                        143
# define PEM_F_GET_NAME                                   144
# define PEM_F_I2B_PVK                                    137
# define PEM_F_I2B_PVK_BIO                                138
# define PEM_F_LOAD_IV                                    101
# define PEM_F_PEM_ASN1_READ                              102
# define PEM_F_PEM_ASN1_READ_BIO                          103
# define PEM_F_PEM_ASN1_WRITE                             104
# define PEM_F_PEM_ASN1_WRITE_BIO                         105
# define PEM_F_PEM_DEF_CALLBACK                           100
# define PEM_F_PEM_DO_HEADER                              106
# define PEM_F_PEM_GET_EVP_CIPHER_INFO                    107
# define PEM_F_PEM_READ                                   108
# define PEM_F_PEM_READ_BIO                               109
# define PEM_F_PEM_READ_BIO_DHPARAMS                      141
# define PEM_F_PEM_READ_BIO_EX                            145
# define PEM_F_PEM_READ_BIO_PARAMETERS                    140
# define PEM_F_PEM_READ_BIO_PRIVATEKEY                    123
# define PEM_F_PEM_READ_DHPARAMS                          142
# define PEM_F_PEM_READ_PRIVATEKEY                        124
# define PEM_F_PEM_SIGNFINAL                              112
# define PEM_F_PEM_WRITE                                  113
# define PEM_F_PEM_WRITE_BIO                              114
# define PEM_F_PEM_WRITE_BIO_PRIVATEKEY_TRADITIONAL       147
# define PEM_F_PEM_WRITE_PRIVATEKEY                       139
# define PEM_F_PEM_X509_INFO_READ                         115
# define PEM_F_PEM_X509_INFO_READ_BIO                     116
# define PEM_F_PEM_X509_INFO_WRITE_BIO                    117

/*
 * PEM reason codes.
 */
# define PEM_R_BAD_BASE64_DECODE                          100
# define PEM_R_BAD_DECRYPT                                101
# define PEM_R_BAD_END_LINE                               102
# define PEM_R_BAD_IV_CHARS                               103
# define PEM_R_BAD_MAGIC_NUMBER                           116
# define PEM_R_BAD_PASSWORD_READ                          104
# define PEM_R_BAD_VERSION_NUMBER                         117
# define PEM_R_BIO_WRITE_FAILURE                          118
# define PEM_R_CIPHER_IS_NULL                             127
# define PEM_R_ERROR_CONVERTING_PRIVATE_KEY               115
# define PEM_R_EXPECTING_PRIVATE_KEY_BLOB                 119
# define PEM_R_EXPECTING_PUBLIC_KEY_BLOB                  120
# define PEM_R_HEADER_TOO_LONG                            128
# define PEM_R_INCONSISTENT_HEADER                        121
# define PEM_R_KEYBLOB_HEADER_PARSE_ERROR                 122
# define PEM_R_KEYBLOB_TOO_SHORT                          123
# define PEM_R_MISSING_DEK_IV                             129
# define PEM_R_NOT_DEK_INFO                               105
# define PEM_R_NOT_ENCRYPTED                              106
# define PEM_R_NOT_PROC_TYPE                              107
# define PEM_R_NO_START_LINE                              108
# define PEM_R_PROBLEMS_GETTING_PASSWORD                  109
# define PEM_R_PVK_DATA_TOO_SHORT                         124
# define PEM_R_PVK_TOO_SHORT                              125
# define PEM_R_READ_KEY                                   111
# define PEM_R_SHORT_HEADER                               112
# define PEM_R_UNEXPECTED_DEK_IV                          130
# define PEM_R_UNSUPPORTED_CIPHER                         113
# define PEM_R_UNSUPPORTED_ENCRYPTION                     114
# define PEM_R_UNSUPPORTED_KEY_COMPONENTS                 126
# define PEM_R_UNSUPPORTED_PUBLIC_KEY_TYPE                110

#endif
