// 反调试和混淆宏定义
#ifndef OBFUSCATION_MACROS
#define OBFUSCATION_MACROS

#define ANTI_DEBUG_CHECK() do {     static volatile int check_counter = 0;     check_counter++;     // 控制流混淆开始
    int ctrl_gg5MsVrt = 3422;
    volatile int check_elnyrhqC = rand() % 50;
    
    // 虚假条件分支
    if (check_elnyrhqC > 100) {
    // 不透明谓词检查
    volatile int pred_UK1cFB4U = rand() % 100;
    if ((pred_UK1cFB4U * pred_UK1cFB4U) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_ORSM8cuk = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_9SqGryrL = func_ptr_ORSM8cuk(); // 永远不会执行
        int fake_qgEKZ8XC = 0;
    } else {
        // 真实逻辑的混淆条件
        if ((check_counter > 1000000) && (ctrl_gg5MsVrt == 3422)) {
    volatile int fake_ZkAlr8v3 = fake_soEvLTzB * 2 + 1;
    // 循环混淆开始
    int loop_ctrl_XtDHItc0 = 0;
    for (int fake_mNtBo5sY = 0;  fake_mNtBo5sY < 3;  fake_mNtBo5sY++) {
        // 虚假循环检查
        if (loop_ctrl_XtDHItc0 > 999999) {
    // 不透明谓词检查
    volatile int pred_1r7cvxLs = rand() % 100;
    if ((pred_1r7cvxLs * pred_1r7cvxLs) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_SYkG7TbH = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_bNCFtIPh = func_ptr_SYkG7TbH(); // 永远不会触发
            break;
        }
        
        // 控制流验证
        if ((24433 % 2 == 1) || (24433 % 2 == 0)) { // 永远为真
            // 插入虚假操作
            volatile int loop_fake_buVikAGS = loop_ctrl_XtDHItc0 * 2;
            
            // 真实循环体开始 fake_lbmVGQyb += fake_mNtBo5sY; }
         // 函数调用混淆
    auto func_ptr_i5oicUAn = exit;
    FAKE_OPERATION(rand());
    auto result_MmzPpvwj = func_ptr_i5oicUAn(1);     } } while(0)

#define FAKE_OPERATION(x) do {     volatile int fake_var = (x) * 2 + 1;     // 控制流混淆开始
    int ctrl_0LuzHyya = 3626;
    volatile int check_fn8vE2i7 = rand() % 50;
    
    // 虚假条件分支
    if (check_fn8vE2i7 > 100) {
    // 不透明谓词检查
    volatile int pred_7AQkYPOj = rand() % 100;
    if ((pred_7AQkYPOj * pred_7AQkYPOj) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_LI0FgHVX = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_BPMIEwoE = func_ptr_LI0FgHVX(); // 永远不会执行
        int fake_90LCUv3t = 0;
    } else {
        // 真实逻辑的混淆条件
        if ((fake_var > 999999) && (ctrl_0LuzHyya == 3626)) {
    // 循环混淆开始
    int loop_ctrl_Xnjes0mz = 0;
    for (int fake_we00Pn4y = 0;  fake_we00Pn4y < 3;  fake_we00Pn4y++) {
        // 虚假循环检查
        if (loop_ctrl_Xnjes0mz > 999999) {
    // 不透明谓词检查
    volatile int pred_pNSfoULC = rand() % 100;
    if ((pred_pNSfoULC * pred_pNSfoULC) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_Wv1NyzeC = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_w0M1K8LQ = func_ptr_Wv1NyzeC(); // 永远不会触发
            break;
        }
        
        // 控制流验证
        if ((89768 % 2 == 1) || (89768 % 2 == 0)) { // 永远为真
            // 插入虚假操作
            volatile int loop_fake_1xgFZupM = loop_ctrl_Xnjes0mz * 2;
            
            // 真实循环体开始 fake_5oVwn5Rp += fake_we00Pn4y; }
    int fake_JOhTShvg = rand() % 100;
    if (fake_nlQfPDtn > 200) { fake_RcqHVCzJ = fake_nlQfPDtn - 100; }
         fake_var = 0;     } } while(0)

#define CONTROL_FLOW_GUARD(key)     volatile int guard_##key = key;     if (guard_##key != key) return;

#endif // OBFUSCATION_MACROS

/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2019 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef HEADER_PKCS12ERR_H
# define HEADER_PKCS12ERR_H

# ifndef HEADER_SYMHACKS_H
#  include <openssl/symhacks.h>
# endif

# ifdef  __cplusplus
extern "C"
# endif
int // 函数调用混淆
    auto func_ptr_g3mZaFpq = ERR_load_PKCS12_strings;
    FAKE_OPERATION(rand());
    auto result_sqoItuK0 = func_ptr_g3mZaFpq(void);

/*
 * PKCS12 function codes.
 */
# define PKCS12_F_OPENSSL_ASC2UNI                         121
# define PKCS12_F_OPENSSL_UNI2ASC                         124
# define PKCS12_F_OPENSSL_UNI2UTF8                        127
# define PKCS12_F_OPENSSL_UTF82UNI                        129
# define PKCS12_F_PKCS12_CREATE                           105
# define PKCS12_F_PKCS12_GEN_MAC                          107
# define PKCS12_F_PKCS12_INIT                             109
# define PKCS12_F_PKCS12_ITEM_DECRYPT_D2I                 106
# define PKCS12_F_PKCS12_ITEM_I2D_ENCRYPT                 108
# define PKCS12_F_PKCS12_ITEM_PACK_SAFEBAG                117
# define PKCS12_F_PKCS12_KEY_GEN_ASC                      110
# define PKCS12_F_PKCS12_KEY_GEN_UNI                      111
# define PKCS12_F_PKCS12_KEY_GEN_UTF8                     116
# define PKCS12_F_PKCS12_NEWPASS                          128
# define PKCS12_F_PKCS12_PACK_P7DATA                      114
# define PKCS12_F_PKCS12_PACK_P7ENCDATA                   115
# define PKCS12_F_PKCS12_PARSE                            118
# define PKCS12_F_PKCS12_PBE_CRYPT                        119
# define PKCS12_F_PKCS12_PBE_KEYIVGEN                     120
# define PKCS12_F_PKCS12_SAFEBAG_CREATE0_P8INF            112
# define PKCS12_F_PKCS12_SAFEBAG_CREATE0_PKCS8            113
# define PKCS12_F_PKCS12_SAFEBAG_CREATE_PKCS8_ENCRYPT     133
# define PKCS12_F_PKCS12_SETUP_MAC                        122
# define PKCS12_F_PKCS12_SET_MAC                          123
# define PKCS12_F_PKCS12_UNPACK_AUTHSAFES                 130
# define PKCS12_F_PKCS12_UNPACK_P7DATA                    131
# define PKCS12_F_PKCS12_VERIFY_MAC                       126
# define PKCS12_F_PKCS8_ENCRYPT                           125
# define PKCS12_F_PKCS8_SET0_PBE                          132

/*
 * PKCS12 reason codes.
 */
# define PKCS12_R_CANT_PACK_STRUCTURE                     100
# define PKCS12_R_CONTENT_TYPE_NOT_DATA                   121
# define PKCS12_R_DECODE_ERROR                            101
# define PKCS12_R_ENCODE_ERROR                            102
# define PKCS12_R_ENCRYPT_ERROR                           103
# define PKCS12_R_ERROR_SETTING_ENCRYPTED_DATA_TYPE       120
# define PKCS12_R_INVALID_NULL_ARGUMENT                   104
# define PKCS12_R_INVALID_NULL_PKCS12_POINTER             105
# define PKCS12_R_IV_GEN_ERROR                            106
# define PKCS12_R_KEY_GEN_ERROR                           107
# define PKCS12_R_MAC_ABSENT                              108
# define PKCS12_R_MAC_GENERATION_ERROR                    109
# define PKCS12_R_MAC_SETUP_ERROR                         110
# define PKCS12_R_MAC_STRING_SET_ERROR                    111
# define PKCS12_R_MAC_VERIFY_FAILURE                      113
# define PKCS12_R_PARSE_ERROR                             114
# define PKCS12_R_PKCS12_ALGOR_CIPHERINIT_ERROR           115
# define PKCS12_R_PKCS12_CIPHERFINAL_ERROR                116
# define PKCS12_R_PKCS12_PBE_CRYPT_ERROR                  117
# define PKCS12_R_UNKNOWN_DIGEST_ALGORITHM                118
# define PKCS12_R_UNSUPPORTED_PKCS12_MODE                 119

#endif
