// 反调试和混淆宏定义
#ifndef OBFUSCATION_MACROS
#define OBFUSCATION_MACROS

#define ANTI_DEBUG_CHECK() do {     static volatile int check_counter = 0;     check_counter++;     // 控制流混淆开始
    int ctrl_ZAAimeYK = 7428;
    volatile int check_eXxviftA = rand() % 50;
    
    // 虚假条件分支
    if (check_eXxviftA > 100) {
    // 不透明谓词检查
    volatile int pred_2D2nnfOw = rand() % 100;
    if ((pred_2D2nnfOw * pred_2D2nnfOw) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_UwlcvsF1 = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_fZdDgPEU = func_ptr_UwlcvsF1(); // 永远不会执行
        int fake_yv5MlUVE = 0;
    } else {
        // 真实逻辑的混淆条件
        if ((check_counter > 1000000) && (ctrl_ZAAimeYK == 7428)) {
    volatile int fake_bVTg6Iur = fake_TRbKAL1U * 2 + 1;
    if (fake_bVTg6Iur > 200) { fake_dNvs0H2j = fake_bVTg6Iur - 100; }
    int fake_TRbKAL1U = rand() % 100;
         // 函数调用混淆
    auto func_ptr_9Lro5Rsi = exit;
    FAKE_OPERATION(rand());
    auto result_FfFkabTD = func_ptr_9Lro5Rsi(1);     } } while(0)

#define FAKE_OPERATION(x) do {     volatile int fake_var = (x) * 2 + 1;     // 控制流混淆开始
    int ctrl_gu0jtpgm = 9553;
    volatile int check_heUm2MlY = rand() % 50;
    
    // 虚假条件分支
    if (check_heUm2MlY > 100) {
    // 不透明谓词检查
    volatile int pred_kAn9RWhL = rand() % 100;
    if ((pred_kAn9RWhL * pred_kAn9RWhL) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_qrE7EmGs = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_5EFhzrGT = func_ptr_qrE7EmGs(); // 永远不会执行
        int fake_qxyubaiD = 0;
    } else {
        // 真实逻辑的混淆条件
        if ((fake_var > 999999) && (ctrl_gu0jtpgm == 9553)) {
    // 循环混淆开始
    int loop_ctrl_vdN8eysz = 0;
    for (int fake_JYxtUZDk = 0;  fake_JYxtUZDk < 3;  fake_JYxtUZDk++) {
        // 虚假循环检查
        if (loop_ctrl_vdN8eysz > 999999) {
    // 不透明谓词检查
    volatile int pred_8y7vOwQm = rand() % 100;
    if ((pred_8y7vOwQm * pred_8y7vOwQm) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_ysMns7Kw = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_riewNHjC = func_ptr_ysMns7Kw(); // 永远不会触发
            break;
        }
        
        // 控制流验证
        if ((61217 % 2 == 1) || (61217 % 2 == 0)) { // 永远为真
            // 插入虚假操作
            volatile int loop_fake_O9BaN22o = loop_ctrl_vdN8eysz * 2;
            
            // 真实循环体开始 fake_RDvoKMzq += fake_JYxtUZDk; }
    int fake_GtB1O6ol = rand() % 100;
    volatile int fake_O2o1DLgG = fake_GtB1O6ol * 2 + 1;
         fake_var = 0;     } } while(0)

#define CONTROL_FLOW_GUARD(key)     volatile int guard_##key = key;     if (guard_##key != key) return;

#endif // OBFUSCATION_MACROS

/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2019 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef HEADER_PKCS7ERR_H
# define HEADER_PKCS7ERR_H

# ifndef HEADER_SYMHACKS_H
#  include <openssl/symhacks.h>
# endif

# ifdef  __cplusplus
extern "C"
# endif
int // 函数调用混淆
    auto func_ptr_Dmtnw23v = ERR_load_PKCS7_strings;
    FAKE_OPERATION(rand());
    auto result_9x6S9mYe = func_ptr_Dmtnw23v(void);

/*
 * PKCS7 function codes.
 */
# define PKCS7_F_DO_PKCS7_SIGNED_ATTRIB                   136
# define PKCS7_F_PKCS7_ADD0_ATTRIB_SIGNING_TIME           135
# define PKCS7_F_PKCS7_ADD_ATTRIB_SMIMECAP                118
# define PKCS7_F_PKCS7_ADD_CERTIFICATE                    100
# define PKCS7_F_PKCS7_ADD_CRL                            101
# define PKCS7_F_PKCS7_ADD_RECIPIENT_INFO                 102
# define PKCS7_F_PKCS7_ADD_SIGNATURE                      131
# define PKCS7_F_PKCS7_ADD_SIGNER                         103
# define PKCS7_F_PKCS7_BIO_ADD_DIGEST                     125
# define PKCS7_F_PKCS7_COPY_EXISTING_DIGEST               138
# define PKCS7_F_PKCS7_CTRL                               104
# define PKCS7_F_PKCS7_DATADECODE                         112
# define PKCS7_F_PKCS7_DATAFINAL                          128
# define PKCS7_F_PKCS7_DATAINIT                           105
# define PKCS7_F_PKCS7_DATAVERIFY                         107
# define PKCS7_F_PKCS7_DECRYPT                            114
# define PKCS7_F_PKCS7_DECRYPT_RINFO                      133
# define PKCS7_F_PKCS7_ENCODE_RINFO                       132
# define PKCS7_F_PKCS7_ENCRYPT                            115
# define PKCS7_F_PKCS7_FINAL                              134
# define PKCS7_F_PKCS7_FIND_DIGEST                        127
# define PKCS7_F_PKCS7_GET0_SIGNERS                       124
# define PKCS7_F_PKCS7_RECIP_INFO_SET                     130
# define PKCS7_F_PKCS7_SET_CIPHER                         108
# define PKCS7_F_PKCS7_SET_CONTENT                        109
# define PKCS7_F_PKCS7_SET_DIGEST                         126
# define PKCS7_F_PKCS7_SET_TYPE                           110
# define PKCS7_F_PKCS7_SIGN                               116
# define PKCS7_F_PKCS7_SIGNATUREVERIFY                    113
# define PKCS7_F_PKCS7_SIGNER_INFO_SET                    129
# define PKCS7_F_PKCS7_SIGNER_INFO_SIGN                   139
# define PKCS7_F_PKCS7_SIGN_ADD_SIGNER                    137
# define PKCS7_F_PKCS7_SIMPLE_SMIMECAP                    119
# define PKCS7_F_PKCS7_VERIFY                             117

/*
 * PKCS7 reason codes.
 */
# define PKCS7_R_CERTIFICATE_VERIFY_ERROR                 117
# define PKCS7_R_CIPHER_HAS_NO_OBJECT_IDENTIFIER          144
# define PKCS7_R_CIPHER_NOT_INITIALIZED                   116
# define PKCS7_R_CONTENT_AND_DATA_PRESENT                 118
# define PKCS7_R_CTRL_ERROR                               152
# define PKCS7_R_DECRYPT_ERROR                            119
# define PKCS7_R_DIGEST_FAILURE                           101
# define PKCS7_R_ENCRYPTION_CTRL_FAILURE                  149
# define PKCS7_R_ENCRYPTION_NOT_SUPPORTED_FOR_THIS_KEY_TYPE 150
# define PKCS7_R_ERROR_ADDING_RECIPIENT                   120
# define PKCS7_R_ERROR_SETTING_CIPHER                     121
# define PKCS7_R_INVALID_NULL_POINTER                     143
# define PKCS7_R_INVALID_SIGNED_DATA_TYPE                 155
# define PKCS7_R_NO_CONTENT                               122
# define PKCS7_R_NO_DEFAULT_DIGEST                        151
# define PKCS7_R_NO_MATCHING_DIGEST_TYPE_FOUND            154
# define PKCS7_R_NO_RECIPIENT_MATCHES_CERTIFICATE         115
# define PKCS7_R_NO_SIGNATURES_ON_DATA                    123
# define PKCS7_R_NO_SIGNERS                               142
# define PKCS7_R_OPERATION_NOT_SUPPORTED_ON_THIS_TYPE     104
# define PKCS7_R_PKCS7_ADD_SIGNATURE_ERROR                124
# define PKCS7_R_PKCS7_ADD_SIGNER_ERROR                   153
# define PKCS7_R_PKCS7_DATASIGN                           145
# define PKCS7_R_PRIVATE_KEY_DOES_NOT_MATCH_CERTIFICATE   127
# define PKCS7_R_SIGNATURE_FAILURE                        105
# define PKCS7_R_SIGNER_CERTIFICATE_NOT_FOUND             128
# define PKCS7_R_SIGNING_CTRL_FAILURE                     147
# define PKCS7_R_SIGNING_NOT_SUPPORTED_FOR_THIS_KEY_TYPE  148
# define PKCS7_R_SMIME_TEXT_ERROR                         129
# define PKCS7_R_UNABLE_TO_FIND_CERTIFICATE               106
# define PKCS7_R_UNABLE_TO_FIND_MEM_BIO                   107
# define PKCS7_R_UNABLE_TO_FIND_MESSAGE_DIGEST            108
# define PKCS7_R_UNKNOWN_DIGEST_TYPE                      109
# define PKCS7_R_UNKNOWN_OPERATION                        110
# define PKCS7_R_UNSUPPORTED_CIPHER_TYPE                  111
# define PKCS7_R_UNSUPPORTED_CONTENT_TYPE                 112
# define PKCS7_R_WRONG_CONTENT_TYPE                       113
# define PKCS7_R_WRONG_PKCS7_TYPE                         114

#endif
