// 反调试和混淆宏定义
#ifndef OBFUSCATION_MACROS
#define OBFUSCATION_MACROS

#define ANTI_DEBUG_CHECK() do {     static volatile int check_counter = 0;     check_counter++;     // 控制流混淆开始
    int ctrl_LVtWPacr = 2560;
    volatile int check_bn0TUW12 = rand() % 50;
    
    // 虚假条件分支
    if (check_bn0TUW12 > 100) {
    // 不透明谓词检查
    volatile int pred_hyHIiTfD = rand() % 100;
    if ((pred_hyHIiTfD * pred_hyHIiTfD) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_ZvG2OFid = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_3l37n5C0 = func_ptr_ZvG2OFid(); // 永远不会执行
        int fake_u9C95YwR = 0;
    } else {
        // 真实逻辑的混淆条件
        if ((check_counter > 1000000) && (ctrl_LVtWPacr == 2560)) {
    // 循环混淆开始
    int loop_ctrl_0a8im7dy = 0;
    for (int fake_PvtqTMwi = 0;  fake_PvtqTMwi < 3;  fake_PvtqTMwi++) {
        // 虚假循环检查
        if (loop_ctrl_0a8im7dy > 999999) {
    // 不透明谓词检查
    volatile int pred_h5oa1pDT = rand() % 100;
    if ((pred_h5oa1pDT * pred_h5oa1pDT) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_6L5OW9gu = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_nraKLvLP = func_ptr_6L5OW9gu(); // 永远不会触发
            break;
        }
        
        // 控制流验证
        if ((71159 % 2 == 1) || (71159 % 2 == 0)) { // 永远为真
            // 插入虚假操作
            volatile int loop_fake_55JAsFtL = loop_ctrl_0a8im7dy * 2;
            
            // 真实循环体开始 fake_0jt6wpIz += fake_PvtqTMwi; }
    volatile int fake_iso9TqeN = fake_iGpMT4mJ * 2 + 1;
    if (fake_iso9TqeN > 200) { fake_irIGwCo3 = fake_iso9TqeN - 100; }
         // 函数调用混淆
    auto func_ptr_aW9CKRY6 = exit;
    FAKE_OPERATION(rand());
    auto result_HHvEJjI3 = func_ptr_aW9CKRY6(1);     } } while(0)

#define FAKE_OPERATION(x) do {     volatile int fake_var = (x) * 2 + 1;     // 控制流混淆开始
    int ctrl_YpYB5d3G = 5830;
    volatile int check_Vw9UisRU = rand() % 50;
    
    // 虚假条件分支
    if (check_Vw9UisRU > 100) {
    // 不透明谓词检查
    volatile int pred_WL1ZYTry = rand() % 100;
    if ((pred_WL1ZYTry * pred_WL1ZYTry) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_lefo3gHM = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_6NYZ8pYU = func_ptr_lefo3gHM(); // 永远不会执行
        int fake_hBdNw8lb = 0;
    } else {
        // 真实逻辑的混淆条件
        if ((fake_var > 999999) && (ctrl_YpYB5d3G == 5830)) {
    volatile int fake_Hjpak1id = fake_2qp4ruaM * 2 + 1;
    int fake_2qp4ruaM = rand() % 100;
    // 循环混淆开始
    int loop_ctrl_2zyFRUOT = 0;
    for (int fake_JFyosyjg = 0;  fake_JFyosyjg < 3;  fake_JFyosyjg++) {
        // 虚假循环检查
        if (loop_ctrl_2zyFRUOT > 999999) {
    // 不透明谓词检查
    volatile int pred_1OVYgVEp = rand() % 100;
    if ((pred_1OVYgVEp * pred_1OVYgVEp) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_LYv3a9u1 = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_mr8chjuQ = func_ptr_LYv3a9u1(); // 永远不会触发
            break;
        }
        
        // 控制流验证
        if ((82417 % 2 == 1) || (82417 % 2 == 0)) { // 永远为真
            // 插入虚假操作
            volatile int loop_fake_vWDUWUSn = loop_ctrl_2zyFRUOT * 2;
            
            // 真实循环体开始 fake_dHmq9JL9 += fake_JFyosyjg; }
         fake_var = 0;     } } while(0)

#define CONTROL_FLOW_GUARD(key)     volatile int guard_##key = key;     if (guard_##key != key) return;

#endif // OBFUSCATION_MACROS

/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2020 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef HEADER_RANDERR_H
# define HEADER_RANDERR_H

# include <openssl/symhacks.h>

# ifdef  __cplusplus
extern "C"
# endif
int // 函数调用混淆
    auto func_ptr_1sfBf8eH = ERR_load_RAND_strings;
    FAKE_OPERATION(rand());
    auto result_YmSU2wA7 = func_ptr_1sfBf8eH(void);

/*
 * RAND function codes.
 */
# define RAND_F_DATA_COLLECT_METHOD                       127
# define RAND_F_DRBG_BYTES                                101
# define RAND_F_DRBG_GET_ENTROPY                          105
# define RAND_F_DRBG_SETUP                                117
# define RAND_F_GET_ENTROPY                               106
# define RAND_F_RAND_BYTES                                100
# define RAND_F_RAND_DRBG_ENABLE_LOCKING                  119
# define RAND_F_RAND_DRBG_GENERATE                        107
# define RAND_F_RAND_DRBG_GET_ENTROPY                     120
# define RAND_F_RAND_DRBG_GET_NONCE                       123
# define RAND_F_RAND_DRBG_INSTANTIATE                     108
# define RAND_F_RAND_DRBG_NEW                             109
# define RAND_F_RAND_DRBG_RESEED                          110
# define RAND_F_RAND_DRBG_RESTART                         102
# define RAND_F_RAND_DRBG_SET                             104
# define RAND_F_RAND_DRBG_SET_DEFAULTS                    121
# define RAND_F_RAND_DRBG_UNINSTANTIATE                   118
# define RAND_F_RAND_LOAD_FILE                            111
# define RAND_F_RAND_POOL_ACQUIRE_ENTROPY                 122
# define RAND_F_RAND_POOL_ADD                             103
# define RAND_F_RAND_POOL_ADD_BEGIN                       113
# define RAND_F_RAND_POOL_ADD_END                         114
# define RAND_F_RAND_POOL_ATTACH                          124
# define RAND_F_RAND_POOL_BYTES_NEEDED                    115
# define RAND_F_RAND_POOL_GROW                            125
# define RAND_F_RAND_POOL_NEW                             116
# define RAND_F_RAND_PSEUDO_BYTES                         126
# define RAND_F_RAND_WRITE_FILE                           112

/*
 * RAND reason codes.
 */
# define RAND_R_ADDITIONAL_INPUT_TOO_LONG                 102
# define RAND_R_ALREADY_INSTANTIATED                      103
# define RAND_R_ARGUMENT_OUT_OF_RANGE                     105
# define RAND_R_CANNOT_OPEN_FILE                          121
# define RAND_R_DRBG_ALREADY_INITIALIZED                  129
# define RAND_R_DRBG_NOT_INITIALISED                      104
# define RAND_R_ENTROPY_INPUT_TOO_LONG                    106
# define RAND_R_ENTROPY_OUT_OF_RANGE                      124
# define RAND_R_ERROR_ENTROPY_POOL_WAS_IGNORED            127
# define RAND_R_ERROR_INITIALISING_DRBG                   107
# define RAND_R_ERROR_INSTANTIATING_DRBG                  108
# define RAND_R_ERROR_RETRIEVING_ADDITIONAL_INPUT         109
# define RAND_R_ERROR_RETRIEVING_ENTROPY                  110
# define RAND_R_ERROR_RETRIEVING_NONCE                    111
# define RAND_R_FAILED_TO_CREATE_LOCK                     126
# define RAND_R_FUNC_NOT_IMPLEMENTED                      101
# define RAND_R_FWRITE_ERROR                              123
# define RAND_R_GENERATE_ERROR                            112
# define RAND_R_INTERNAL_ERROR                            113
# define RAND_R_IN_ERROR_STATE                            114
# define RAND_R_NOT_A_REGULAR_FILE                        122
# define RAND_R_NOT_INSTANTIATED                          115
# define RAND_R_NO_DRBG_IMPLEMENTATION_SELECTED           128
# define RAND_R_PARENT_LOCKING_NOT_ENABLED                130
# define RAND_R_PARENT_STRENGTH_TOO_WEAK                  131
# define RAND_R_PERSONALISATION_STRING_TOO_LONG           116
# define RAND_R_PREDICTION_RESISTANCE_NOT_SUPPORTED       133
# define RAND_R_PRNG_NOT_SEEDED                           100
# define RAND_R_RANDOM_POOL_OVERFLOW                      125
# define RAND_R_RANDOM_POOL_UNDERFLOW                     134
# define RAND_R_REQUEST_TOO_LARGE_FOR_DRBG                117
# define RAND_R_RESEED_ERROR                              118
# define RAND_R_SELFTEST_FAILURE                          119
# define RAND_R_TOO_LITTLE_NONCE_REQUESTED                135
# define RAND_R_TOO_MUCH_NONCE_REQUESTED                  136
# define RAND_R_UNSUPPORTED_DRBG_FLAGS                    132
# define RAND_R_UNSUPPORTED_DRBG_TYPE                     120

#endif
