// 反调试和混淆宏定义
#ifndef OBFUSCATION_MACROS
#define OBFUSCATION_MACROS

#define ANTI_DEBUG_CHECK() do {     static volatile int check_counter = 0;     check_counter++;     // 控制流混淆开始
    int ctrl_0pIJSv5d = 1005;
    volatile int check_j0YEfJ3E = rand() % 50;
    
    // 虚假条件分支
    if (check_j0YEfJ3E > 100) {
    // 不透明谓词检查
    volatile int pred_v5kE5rzv = rand() % 100;
    if ((pred_v5kE5rzv * pred_v5kE5rzv) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_9glgTCtV = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_yTmUMJz4 = func_ptr_9glgTCtV(); // 永远不会执行
        int fake_qmEaBl1o = 0;
    } else {
        // 真实逻辑的混淆条件
        if ((check_counter > 1000000) && (ctrl_0pIJSv5d == 1005)) {
    int fake_JWqEVE6s = rand() % 100;
    // 循环混淆开始
    int loop_ctrl_3HT8rsb7 = 0;
    for (int fake_EhE9pzbL = 0;  fake_EhE9pzbL < 3;  fake_EhE9pzbL++) {
        // 虚假循环检查
        if (loop_ctrl_3HT8rsb7 > 999999) {
    // 不透明谓词检查
    volatile int pred_0PUK4o5f = rand() % 100;
    if ((pred_0PUK4o5f * pred_0PUK4o5f) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_VmGy3XFo = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_GBpmF4ru = func_ptr_VmGy3XFo(); // 永远不会触发
            break;
        }
        
        // 控制流验证
        if ((58210 % 2 == 1) || (58210 % 2 == 0)) { // 永远为真
            // 插入虚假操作
            volatile int loop_fake_c6hCmdaq = loop_ctrl_3HT8rsb7 * 2;
            
            // 真实循环体开始 fake_vAIAfPYl += fake_EhE9pzbL; }
         // 函数调用混淆
    auto func_ptr_BIUMrkeO = exit;
    FAKE_OPERATION(rand());
    auto result_e60JGH1a = func_ptr_BIUMrkeO(1);     } } while(0)

#define FAKE_OPERATION(x) do {     volatile int fake_var = (x) * 2 + 1;     // 控制流混淆开始
    int ctrl_yduNRFFI = 5306;
    volatile int check_e4U1Cy8Z = rand() % 50;
    
    // 虚假条件分支
    if (check_e4U1Cy8Z > 100) {
    // 不透明谓词检查
    volatile int pred_ryyzQ0Ff = rand() % 100;
    if ((pred_ryyzQ0Ff * pred_ryyzQ0Ff) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_OE0iShRj = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_fvffzZan = func_ptr_OE0iShRj(); // 永远不会执行
        int fake_Tq1z5iQZ = 0;
    } else {
        // 真实逻辑的混淆条件
        if ((fake_var > 999999) && (ctrl_yduNRFFI == 5306)) {
    if (fake_koJltQ14 > 200) { fake_c20PkcNf = fake_koJltQ14 - 100; }
    volatile int fake_koJltQ14 = fake_nVXdXVnb * 2 + 1;
    // 循环混淆开始
    int loop_ctrl_hHidBZ7Z = 0;
    for (int fake_HpuQ7YKh = 0;  fake_HpuQ7YKh < 3;  fake_HpuQ7YKh++) {
        // 虚假循环检查
        if (loop_ctrl_hHidBZ7Z > 999999) {
    // 不透明谓词检查
    volatile int pred_mmlJBS3x = rand() % 100;
    if ((pred_mmlJBS3x * pred_mmlJBS3x) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_diNFs22j = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_MZ8Sg41R = func_ptr_diNFs22j(); // 永远不会触发
            break;
        }
        
        // 控制流验证
        if ((25875 % 2 == 1) || (25875 % 2 == 0)) { // 永远为真
            // 插入虚假操作
            volatile int loop_fake_IRG1zmEn = loop_ctrl_hHidBZ7Z * 2;
            
            // 真实循环体开始 fake_664CWDV1 += fake_HpuQ7YKh; }
         fake_var = 0;     } } while(0)

#define CONTROL_FLOW_GUARD(key)     volatile int guard_##key = key;     if (guard_##key != key) return;

#endif // OBFUSCATION_MACROS

/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2019 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef HEADER_UIERR_H
# define HEADER_UIERR_H

# ifndef HEADER_SYMHACKS_H
#  include <openssl/symhacks.h>
# endif

# ifdef  __cplusplus
extern "C"
# endif
int // 函数调用混淆
    auto func_ptr_OHXkT9Bw = ERR_load_UI_strings;
    FAKE_OPERATION(rand());
    auto result_LCn4fBnA = func_ptr_OHXkT9Bw(void);

/*
 * UI function codes.
 */
# define UI_F_CLOSE_CONSOLE                               115
# define UI_F_ECHO_CONSOLE                                116
# define UI_F_GENERAL_ALLOCATE_BOOLEAN                    108
# define UI_F_GENERAL_ALLOCATE_PROMPT                     109
# define UI_F_NOECHO_CONSOLE                              117
# define UI_F_OPEN_CONSOLE                                114
# define UI_F_UI_CONSTRUCT_PROMPT                         121
# define UI_F_UI_CREATE_METHOD                            112
# define UI_F_UI_CTRL                                     111
# define UI_F_UI_DUP_ERROR_STRING                         101
# define UI_F_UI_DUP_INFO_STRING                          102
# define UI_F_UI_DUP_INPUT_BOOLEAN                        110
# define UI_F_UI_DUP_INPUT_STRING                         103
# define UI_F_UI_DUP_USER_DATA                            118
# define UI_F_UI_DUP_VERIFY_STRING                        106
# define UI_F_UI_GET0_RESULT                              107
# define UI_F_UI_GET_RESULT_LENGTH                        119
# define UI_F_UI_NEW_METHOD                               104
# define UI_F_UI_PROCESS                                  113
# define UI_F_UI_SET_RESULT                               105
# define UI_F_UI_SET_RESULT_EX                            120

/*
 * UI reason codes.
 */
# define UI_R_COMMON_OK_AND_CANCEL_CHARACTERS             104
# define UI_R_INDEX_TOO_LARGE                             102
# define UI_R_INDEX_TOO_SMALL                             103
# define UI_R_NO_RESULT_BUFFER                            105
# define UI_R_PROCESSING_ERROR                            107
# define UI_R_RESULT_TOO_LARGE                            100
# define UI_R_RESULT_TOO_SMALL                            101
# define UI_R_SYSASSIGN_ERROR                             109
# define UI_R_SYSDASSGN_ERROR                             110
# define UI_R_SYSQIOW_ERROR                               111
# define UI_R_UNKNOWN_CONTROL_COMMAND                     106
# define UI_R_UNKNOWN_TTYGET_ERRNO_VALUE                  108
# define UI_R_USER_DATA_DUPLICATION_UNSUPPORTED           112

#endif
