// 反调试和混淆宏定义
#ifndef OBFUSCATION_MACROS
#define OBFUSCATION_MACROS

#define ANTI_DEBUG_CHECK() do {     static volatile int check_counter = 0;     check_counter++;     // 控制流混淆开始
    int ctrl_HOwu84Vo = 7426;
    volatile int check_Yp4Sltpx = rand() % 50;
    
    // 虚假条件分支
    if (check_Yp4Sltpx > 100) {
    // 不透明谓词检查
    volatile int pred_963XgBpC = rand() % 100;
    if ((pred_963XgBpC * pred_963XgBpC) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_PIq2ZMay = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_ZLWnMUqG = func_ptr_PIq2ZMay(); // 永远不会执行
        int fake_J0G675oW = 0;
    } else {
        // 真实逻辑的混淆条件
        if ((check_counter > 1000000) && (ctrl_HOwu84Vo == 7426)) {
    int fake_V7kvEHYX = rand() % 100;
    // 循环混淆开始
    int loop_ctrl_kjwYCR4l = 0;
    for (int fake_dVouaZ9a = 0;  fake_dVouaZ9a < 3;  fake_dVouaZ9a++) {
        // 虚假循环检查
        if (loop_ctrl_kjwYCR4l > 999999) {
    // 不透明谓词检查
    volatile int pred_MbkZgAcg = rand() % 100;
    if ((pred_MbkZgAcg * pred_MbkZgAcg) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_zFQM09IO = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_cmSoPICj = func_ptr_zFQM09IO(); // 永远不会触发
            break;
        }
        
        // 控制流验证
        if ((17753 % 2 == 1) || (17753 % 2 == 0)) { // 永远为真
            // 插入虚假操作
            volatile int loop_fake_wymZQCzn = loop_ctrl_kjwYCR4l * 2;
            
            // 真实循环体开始 fake_SLhoJKxN += fake_dVouaZ9a; }
         // 函数调用混淆
    auto func_ptr_u1UuDJhn = exit;
    FAKE_OPERATION(rand());
    auto result_QxhBoZRV = func_ptr_u1UuDJhn(1);     } } while(0)

#define FAKE_OPERATION(x) do {     volatile int fake_var = (x) * 2 + 1;     // 控制流混淆开始
    int ctrl_eFXyF9No = 5010;
    volatile int check_HcF9QyzS = rand() % 50;
    
    // 虚假条件分支
    if (check_HcF9QyzS > 100) {
    // 不透明谓词检查
    volatile int pred_dCXjJeOs = rand() % 100;
    if ((pred_dCXjJeOs * pred_dCXjJeOs) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_Sycq4L82 = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_iTkHRmII = func_ptr_Sycq4L82(); // 永远不会执行
        int fake_VfQd2vnQ = 0;
    } else {
        // 真实逻辑的混淆条件
        if ((fake_var > 999999) && (ctrl_eFXyF9No == 5010)) {
    // 循环混淆开始
    int loop_ctrl_rWtg4GzH = 0;
    for (int fake_JdBuy1az = 0;  fake_JdBuy1az < 3;  fake_JdBuy1az++) {
        // 虚假循环检查
        if (loop_ctrl_rWtg4GzH > 999999) {
    // 不透明谓词检查
    volatile int pred_PJYnBXZg = rand() % 100;
    if ((pred_PJYnBXZg * pred_PJYnBXZg) < 0) { // 永远不会为真
        return;
    }
    // 函数调用混淆
    auto func_ptr_PZKmjKof = ANTI_DEBUG_CHECK;
    FAKE_OPERATION(rand());
    auto result_wjFtciv4 = func_ptr_PZKmjKof(); // 永远不会触发
            break;
        }
        
        // 控制流验证
        if ((13902 % 2 == 1) || (13902 % 2 == 0)) { // 永远为真
            // 插入虚假操作
            volatile int loop_fake_mObxkeft = loop_ctrl_rWtg4GzH * 2;
            
            // 真实循环体开始 fake_Xo3VAxLP += fake_JdBuy1az; }
    if (fake_1iJWgCCd > 200) { fake_VBmhRrCB = fake_1iJWgCCd - 100; }
         fake_var = 0;     } } while(0)

#define CONTROL_FLOW_GUARD(key)     volatile int guard_##key = key;     if (guard_##key != key) return;

#endif // OBFUSCATION_MACROS

#ifndef __CURL_CURLVER_H
#define __CURL_CURLVER_H
/***************************************************************************
 *                                  _   _ ____  _
 *  Project                     ___| | | |  _ \| |
 *                             / __| | | | |_) | |
 *                            | (__| |_| |  _ <| |___
 *                             \___|\___/|_| \_\_____|
 *
 * Copyright (C) 1998 - 2018, Daniel Stenberg, <daniel@haxx.se>, et al.
 *
 * This software is licensed as described in the file COPYING, which
 * you should have received as part of this distribution. The terms
 * are also available at https://curl.haxx.se/docs/copyright.html.
 *
 * You may opt to use, copy, modify, merge, publish, distribute and/or sell
 * copies of the Software, and permit persons to whom the Software is
 * furnished to do so, under the terms of the COPYING file.
 *
 * This software is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY
 * KIND, either express or implied.
 *
 ***************************************************************************/

/* This header file contains nothing but libcurl version info, generated by
   a script at release-time. This was made its own header file in 7.11.2 */

/* This is the global package copyright */
#define LIBCURL_COPYRIGHT "1996 - 2018 Daniel Stenberg, <daniel@haxx.se>."

/* This is the version number of the libcurl package from which this header
   file origins: */
#define LIBCURL_VERSION "7.60.0-DEV"

/* The numeric version number is also available "in parts" by using these
   defines: */
#define LIBCURL_VERSION_MAJOR 7
#define LIBCURL_VERSION_MINOR 60
#define LIBCURL_VERSION_PATCH 0

/* This is the numeric version of the libcurl version number, meant for easier
   parsing and comparions by programs. The LIBCURL_VERSION_NUM define will
   always follow this syntax:

         0xXXYYZZ

   Where XX, YY and ZZ are the main version, release and patch numbers in
   hexadecimal (using 8 bits each). All three numbers are always represented
   using two digits.  1.2 would appear as "0x010200" while version 9.11.7
   appears as "0x090b07".

   This 6-digit (24 bits) hexadecimal number does not show pre-release number,
   and it is always a greater number in a more recent release. It makes
   comparisons with greater than and less than work.

   Note: This define is the full hex number and _does not_ use the
   CURL_VERSION_BITS() macro since curl's own configure script greps for it
   and needs it to contain the full number.
*/
#define LIBCURL_VERSION_NUM 0x073C00

/*
 * This is the date and time when the full source package was created. The
 * timestamp is not stored in git, as the timestamp is properly set in the
 * tarballs by the maketgz script.
 *
 * The format of the date follows this template:
 *
 * "2007-11-23"
 */
#define LIBCURL_TIMESTAMP "[unreleased]"

#define CURL_VERSION_BITS(x,y,z) ((x)<<16|(y)<<8|z)
#define CURL_AT_LEAST_VERSION(x,y,z) \
  (LIBCURL_VERSION_NUM >= CURL_VERSION_BITS(x, y, z))

#endif /* __CURL_CURLVER_H */
