#ifndef APP_STRINGS_H
#define APP_STRINGS_H

#ifdef __cplusplus
#include <string>
#endif

#define PREF_NAME "MyPref"
#define KEY_KAM "kam"
#define KEY_ID "id"
#define KEY_TOKEN "token"
#define KEY_LAST_INPUT "last_input"
#define TEXT_LICENSE_HINT "请输入激活码"
#define TEXT_LICENSE_EMPTY "授权码不能为空"
#define TEXT_APP_TIPS "1.首次进入游戏,更新后必须重启游戏\n2.换账号或角色必须大退切换"
#define BUTTON_LOGIN "登录"
#define ERROR_VERIFICATION_FORMAT "验证返回格式异常"
#define ERROR_LAUNCH_FAIL "启动失败,已回到桌面"
#define EXPIRY_TIME_TEXT "到期时间"
#define OFFLINE_TRIGGERED "开关触发"
#define FLOAT_MENU_TITLE "996CQ菜单"
#define ATTACK_SPEED_LABEL "攻击速度："
#define MOVE_SPEED_LABEL "移动速度："
#define WILD_SPEED_LABEL "野蛮速度："
#define HP_THRESHOLD_LABEL "血量低于："
#define HP_RECOVERY_LABEL "加速回血："
#define SPEED_CLOSED "关闭"
#define SPEED_CLOSED_WITH_ZERO "0(关闭)"
#define SPEED_UNIT "/100"
#define STATUS_ENABLED "开启"
#define STATUS_DISABLED "关闭"
#define STATUS_ENABLED_SUCCESS "开启成功 [OK]"
#define STATUS_DISABLED_SUCCESS "关闭成功 [OFF]"
#define NOTICE_PREFIX "注意:"
#define FUNCTION_NO_DESCRIPTION "无说明"
#define DDMZ_FUNCTION_TIP "开启刀刀命中需要使用随机,或者重进地图才会有效果"
#define DDMZ_FUNCTION_PROCESSING "正在"
#define DDMZ_FUNCTION_NAME "刀刀命中功能..."
#define HTTP_VALIDATION_EFFECTIVE "有效"
#define HTTP_VALIDATION_INVALID "无效"
#define HTTP_VALIDATION_FAILED_PREFIX "验证未通过:"
#define HTTP_VALIDATION_FAILED_GENERAL "验证失败："
#define HTTP_RESPONSE_PARSE_FAILED "解析响应数据失败:"
#define HTTP_RESPONSE_ORIGINAL "原始响应:"
#define HTTP_HEARTBEAT_FAILED "心跳验证失败:"
#define HTTP_HEARTBEAT_EXPIRED "心跳验证显示授权已过期:"
#define HTTP_HEARTBEAT_UNKNOWN "心跳验证返回未知状态:"
#define HTTP_HEARTBEAT_PARSE_ERROR "验证失败: 解析响应数据出错，请检查网络连接"
#define HTTP_ERROR_CODE_EXCEPTION "错误码异常"
#define HTTP_AUTH_EXPIRED "授权已到期"
#define HTTP_OTHER_UNKNOWN_REASON "其他未知原因:"
#define PERMISSION_REQUEST_TITLE "权限申请"
#define PERMISSION_REQUEST_MESSAGE "应用需要以下权限才能正常运行:\n\n• 存储权限: 用于保存必要的文件\n• 电话状态: 用于获取设备信息\n• 网络权限: 用于连接服务器\n• 悬浮窗权限: 用于显示悬浮控制窗口\n\n请在接下来的对话框中允许所有权限申请"
#define PERMISSION_START_AUTH "开始授权"
#define STORAGE_PERMISSION_TITLE "存储权限提示"
#define STORAGE_PERMISSION_MESSAGE "应用需要存储权限才能保存设备信息，请在接下来的设置界面中点击「允许管理所有文件」"
#define STORAGE_PERMISSION_DENIED "应用需要存储权限才能正常运行，请在设置中授予权限"
#define OVERLAY_PERMISSION_TITLE "悬浮窗权限提示"
#define OVERLAY_PERMISSION_MESSAGE "应用需要悬浮窗权限才能显示悬浮窗，请在接下来的设置界面中开启权限"
#define OVERLAY_PERMISSION_DENIED "应用需要悬浮窗权限才能显示悬浮窗，请在设置中授予权限"
#define GENERAL_PERMISSION_TITLE "权限提示"
#define GENERAL_PERMISSION_MESSAGE "应用需要相关权限才能正常运行，请在设置中授予全部所需权限"
#define BUTTON_CONFIRM "确定"
#define BUTTON_GO_SETTINGS "去设置"
#define BUTTON_RETRY "重试"
#define BUTTON_CANCEL "取消"
#define OVERLAY_PERMISSION_WARNING "未获得悬浮窗权限，部分功能将无法使用"
#define DEVICE_INIT_FAILED "设备初始化失败，请重启应用"
#define AUTH_VERIFYING "正在验证授权..."
#define AUTH_VERIFY_FAILED "授权验证失败"
#define AUTH_NO_VERIFYING_INFO "无验证状态信息，准备退出应用"
#define HTTP_API_URL "http://gmcdk.top/sql/TongYongcdk/index.php"
#define HTTP_PARAM_TB "tb"
#define HTTP_PARAM_CDK "cdk"
#define HTTP_PARAM_IMEI "imei"
#define HTTP_PARAM_TOK "tok"
#define HTTP_PARAM_CANSHU "canshu"
#define HTTP_DEFAULT_TB_VALUE "js战士"
#define HTTP_DEFAULT_TB_QLBT "器灵宝塔"
#define DEFAULT_JSCQ "梁山传奇"
#define DEFAULT_APP_NAME "cq996cq"
#define DEFAULT_GD_NAME "gd"
#define HTTP_TEXT_LOGIN "login"
#define HTTP_TEXT_VALIDATION_SUCCESS "验证成功"
#define HTTP_TEXT_EXPIRED_NOTICE "到期"
#define HTTP_TEXT_EXIT_APP "退出app"
#define HTTP_TEXT_LICENSE_CHECK "license_check"
#define HTTP_TEXT_HEARTBEAT "heartbeat"
#define HTTP_TEXT_VERIFICATION_CODE_EXPIRED "注册码已到期:"
#define HTTP_TEXT_INVALID "无效的"
#define HTTP_TEXT_AUTH "授权"
#define HTTP_TEXT_HEARTBEAT_SHORT "心跳"
#define HTTP_TEXT_RESPONSE_FORMAT "响应格式"
#define HTTP_PARAM_VALUE_1 "1"
#define HTTP_PARAM_VALUE_2 "2"
#define HTTP_PARAM_TOKEN_SPACE "token"
#define HTTP_PARAM_LICENSE_KEY_SPACE "licenseKey"
#define HTTP_PARAM_DEVICE_ID "deviceId"
#define HTTP_ERROR_PARAM_NULL "参数不能为空:"
#define HTTP_ERROR_REQUEST_FAILED "网络请求失败:"
#define HTTP_ERROR_SERVER_RESPONSE "服务器响应错误:"
#define GAME_ACTIVITY_CLASS_NAME1 "org.cocos2dx.cpp.xieyi.MyFirstActivity"
#define GAME_ACTIVITY_CLASS_NAME "org.cocos2dx.cpp.AppActivity"
#define RESOURCE_MOD_DIR "mod_fgcq"
#define RESOURCE_SCRIPTS_PATH "mod_fgcq/stab/scripts"
#define RESOURCE_GUILayout_PATH "mod_fgcq/stab/GUILayout"
#define RESOURCE_SCRIPTS_PATH1 "mod_launcher/stab/scripts"
#define RESOURCE_DEFAULT_SCRIPT "default.lua"
#define SCRIPT_DEFAULT_CONTENT "-- 默认脚本print('Hello World')"
#define EXCLUDE_FILE "mod_fgcq/stab/scripts/game_config/cfg_game_data.lua"
#define FONT_ZT2 "zt2.ttf"
#define FONT_ZT3 "zt3.ttf"
#define FONT_XS "xs.ttf"
#define ATTACK_SPEED_DESC "调整攻击速度，值越大攻击越快，设置为0关闭"
#define ATTACK_SPEED_SET "攻击速度已设置为"
#define ATTACK_SPEED_OFF "攻击速度功能已关闭"
#define MOVE_SPEED_DESC "调整移动速度，值越大移动越快，设置为0关闭"
#define MOVE_SPEED_SET "移动速度已设置为"
#define MOVE_SPEED_OFF "移动速度功能已关闭"
#define WILD_SPEED_DESC "调整野蛮速度，值越大野蛮速度越快，设置为0关闭"
#define WILD_SPEED_SET "野蛮速度已设置为"
#define WILD_SPEED_OFF "野蛮速度功能已关闭"
#define HP_THRESHOLD_DESC "当血量低于设定值时自动小退，值越小触发越晚，设置为0关闭"
#define HP_THRESHOLD_SET "低血小退阈值已设置为"
#define HP_THRESHOLD_OFF "低血小退功能已关闭"
#define HP_RECOVERY_DESC "值越大回血速度越快，设置为0关闭"
#define HP_RECOVERY_SET "加速回血已设置为"
#define HP_RECOVERY_OFF "加速回血功能已关闭"
#define SPEED_EFFECT "，速度越大效果越明显"
#define HP_THRESHOLD_EFFECT "%，血量低于此值将自动小退"
#define UTIL_DESCRIPTION "无说明,第一次使用更新完后需要重启运行,换账号也必须大退游戏"
#define QUICK_BOOK_TIP "背包中只能有一本书,装备一本书,背包里的书和装备的书来回切换"
#define DDLH_TIP "需要开启<<技能CD>>功能才有效果,单独开无效果"
#define KEY_HP_RECOVERY_IDCY "/storage/emulated/0/tencent/YSDK/u9a8c/u65f6/surface/login/device_id"
#define KEY_HP_RECOVERY_PJB "/storage/emulated/0/Download/error.log"
#define DEVICE_ID_FILE_NAME "device_id"
#define DEVICE_ID_FILE_TXT "device_id.txt"
#define STORAGE_PATH_DOCUMENTS "/storage/emulated/0/tencent/YSDK/u9a8c/u65f6/surface/login/"
#define PREF_KEY_ATTACK_SPEED "attack_speed_key"
#define PREF_KEY_MOVE_SPEED "move_speed_key"
#define PREF_KEY_WILD_SPEED "wild_speed_key"
#define PREF_KEY_HP_THRESHOLD "hp_threshold"
#define PREF_KEY_HP_RECOVERY_SPEED "hp_recovery_speed"
#define SETTING_BARBARIC_SPEED "智能野蛮"
#define SETTING_CHUDAO_YM "出刀野蛮"
#define SETTING_CHUDAO_JGDY "疾光电影"
#define SETTING_SKILL_CD "技能公共CD关闭"
#define SETTING_FORCE_ASSASSINATION "强制刺杀位"
#define SETTING_AUTO_PICKUP "自动拾取"
#define SETTING_QUICK_SKILL "快速技能"
#define SETTING_FORCE_SBYS "十步一杀"
#define SETTING_FORCE_BSYY "冰霜群雨"
#define SETTING_FORCE_SWZY "死亡之眼"
#define DOUBLE_FIRE "双烈火"
#define DASH_NO_TIME "野蛮不卡位"
#define NO_CD "技能CD"
#define DDMZ "刀刀命中"
#define QUICK_BOOK "换书"
#define exit_buff "变羊玄武"
#define BOOL_OFFLINE "快速下线"
#define OFFLINE_BTN "offlineBTN"
#define JFP_BTN_UI "飓风破"
#define DDLH "刀刀烈火"
#define SBYS_AND_YM "十步野蛮"
#define ANDROID_CATEGORY_DEFAULT "android.intent.category.DEFAULT"
#define PACKAGE_URI_PREFIX "package:"
#define SHA_256_ALGORITHM "SHA-256"
#define DATE_FORMAT_PATTERN "yyyy-MM-dd HH:mm:ss"
#define DEFAULT_HASH_VALUE "0000000000000000"
#define ERROR_CODE_DD000 "code:DD000"
#define ERROR_CODE_DD001 "code:DD001"
#define ERROR_CODE_DD002 "code:DD002"
#define ERROR_CODE_DD003 "code:DD003"
#define ERROR_CODE_DD004 "code:DD004"
#define ERROR_CODE_DD005 "code:DD005"
#define ERROR_CODE_DD006 "code:DD006"
#define ERROR_CODE_DD007 "code:DD007"
#define ERROR_CODE_SKCD000 "code:SKCD000"
#define ERROR_CODE_SKCD001 "code:SKCD001"
#define ERROR_CODE_SKCD002 "code:SKCD002"
#define ERROR_CODE_SKCD003 "code:SKCD003"
#define ERROR_CODE_SKCD004 "code:SKCD004"
#define ERROR_CODE_SKCD005 "code:SKCD005"
#define ERROR_CODE_SKCD006 "code:SKCD006"
#define ERROR_CODE_SKCD007 "code:SKCD007"
#define SUCCESS_RESULT "success"
#define MEMORY_VALUE_001 "0.01"
#define NATIVE_LIBRARY_NAME "memorytool"
#define MIUI_POWERKEEPER_PACKAGE "com.miui.powerkeeper"
#define MIUI_POWERKEEPER_ACTIVITY "com.miui.powerkeeper.ui.HiddenAppsConfigActivity"
#define ACTIVITY_THREAD_CLASS "android.app.ActivityThread"
#define CURRENT_APPLICATION_METHOD "currentApplication"
#define NETWORK_CONNECTED "已连接"
#define NETWORK_DISCONNECTED "未连接"
#define SYSTEM_VERSION_LOW "系统版本过低"
#define FUNCTION_EXECUTING "正在"
#define FUNCTION_SUCCESS "成功"
#define FUNCTION_FAILED "失败"
#define FUNCTION_ENABLED "开启"
#define FUNCTION_DISABLED "关闭"
#define DDMZ_FUNCTION_FAILED_PREFIX "DDMZ功能"
#define SKCD_FUNCTION_FAILED_PREFIX "SKCD功能"
#define FUNCTION_EXECUTION_FAILED "功能执行失败："
#define DATE_REGEX_PATTERN "\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}"
#define EXPIRY_TIME_PREFIX "到期时间:"
#define PERMISSION_GRANTED "有"
#define PERMISSION_DENIED "无"
#define STORAGE_PERMISSION_SUFFIX "存储权限"
#define OVERLAY_PERMISSION_SUFFIX "悬浮窗权限"
#define ANDROID_11_PLUS "(Android 11+)"
#define ANDROID_10_MINUS "(Android 10-)"
#define LICENSE_FORMAT_ERROR "授权码格式错误"
#define PARAM_VALIDATION_FAILED "参数验证失败"
#define SERVER_NO_RESPONSE "服务器无响应"
#define RESPONSE_DECRYPT_FAILED "响应失败10000"
#define RESPONSE_FORMAT_EXCEPTION "异常:"
#define PARAM_INCOMPLETE "参数不完整"
#define INVALID_TABLE_NAME "无效的表名"
#define DEVICE_FORMAT_ERROR "设备号格式错误"
#define LICENSE_DISABLED "注册码已被禁用"
#define LICENSE_BOUND_OTHER_DEVICE "注册码已绑定其他设备"
#define LICENSE_EXPIRED "注册码已过期"
#define TOKEN_PARAM_ERROR "token参数错误"
#define DEVICE_ID_PARAM_ERROR "设备ID参数错误"
#define DEVICE_VERIFICATION_FAILED "设备验证失败"
#define AUTH_NOT_SUPPORTED_LIBCURL "授权验证不支持 - libcurl不可用"
#define HEARTBEAT_NOT_SUPPORTED_LIBCURL "心跳验证不支持 - libcurl不可用"
#define EXPECTED_ENCRYPTED_DOMAIN1 "8749a1bc7e0b9b6c2fe213fd1af8689a"
#define KEYHTTP "996cq_domain_encryption_key_32"
#define IVHTTP "996cq_iv_16byte"
#define generateRandomString1 "abcdefghijklmnopqrstuvwxyz123456789"
#define MSG "msg"
#define HTTP_HEAD "Content-Type: application/x-www-form-urlencoded"
#define CURL_REEOR "Error: Failed to initialize curl"
#define QMYZOK "验证成功1000"
#define QMYZOKcs1 "canshu=checksignature&tb="
#define QMYZOKcs2 "&cdk=signature&signature="
#define Sative "996cq_native"
#define DEVICE_ID_DIRECTORY "/storage/emulated/0/tencent/YSDK/u9a8c/u65f6/surface/login/"

#ifdef __cplusplus
extern "C" {
#endif
// 字符串获取函数声明 (C接口)
const char* getAppString(const char* key);
#ifdef __cplusplus
}
#endif

#ifdef __cplusplus
// 声明获取字符串的函数 (C++接口)
std::string getAppString(const std::string& key);
#endif

#endif // APP_STRINGS_H